(() => {
  const dashboard = globalThis.applianceDashboard;
  if (!dashboard || typeof dashboard.registerProducts !== "function") {
    throw new Error("appliance dashboard registry is not ready");
  }

  const CHECKED_AT = "2026-09-01";
  const NO_COMMON_ISSUE = "截至查核日，查無達門檻的集中負評／災情";
  const queryUrl = (query) => `https://www.google.com/search?q=${encodeURIComponent(query)}`;
  const directIssueModels = new Set(["2115100119403", "2115100027647"]);
  const issueSources = (model) => directIssueModels.has(model) ? [
    {
      platform: "PTT",
      query: model,
      targetHost: "ptt.cc",
      queryUrl: `https://www.ptt.cc/bbs/LivingGoods/search?q=${encodeURIComponent(model)}`,
    },
    {
      platform: "Mobile01",
      query: model,
      targetHost: "mobile01.com",
      queryUrl: `https://www.mobile01.com/googlesearch.php?q=${encodeURIComponent(model)}`,
    },
  ] : [
    {
      platform: "PTT",
      query: `site:ptt.cc "${model}" (問題 OR 災情 OR 負評)`,
      targetHost: "ptt.cc",
      queryUrl: queryUrl(`site:ptt.cc "${model}" (問題 OR 災情 OR 負評)`),
    },
    {
      platform: "Mobile01",
      query: `site:mobile01.com "${model}" (問題 OR 災情 OR 負評)`,
      targetHost: "mobile01.com",
      queryUrl: queryUrl(`site:mobile01.com "${model}" (問題 OR 災情 OR 負評)`),
    },
  ];

  const warrantyByBrand = {
    IKEA: "IKEA 台灣官方新品；售後、退換與瑕疵處理依台灣官方條款及購買憑證，貼身寢具拆封前先確認尺寸。",
    NITORI: "NITORI 宜得利台灣官方新品與售後；官方頁列 14 天內退換，實際須符合退換條件並保留購買憑證。",
    HOLA: "HOLA 和樂台灣官方新品與售後；退換與瑕疵處理依官方條款及購買憑證，貼身寢具拆封前先確認尺寸。",
  };

  const products = [
    {
      id: "bedsheet-nitori-2115100136769",
      brand: "NITORI",
      model: "2115100136769",
      name: "素色天絲床包 NV 雙人 150×186 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "素色天絲床包",
      topPick: true,
      price: 1190,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100136769_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100136769",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人 NV 版本，SKU 2115100136769",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 萊賽爾纖維（天絲）",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：一般雙人床墊；購買前量測床墊寬、長與厚度",
        "尺寸：寬 150 x 深 186 x 高 27 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：BSMI M73803；台灣製",
        "清潔保養：裝洗衣袋機洗；不可漂白、不可烘乾",
        "重量：查不到",
      ],
      focus: "親膚滑順、吸濕透氣，且有台灣官方商城與售後邊界可核對。",
      drawback: "天絲需避免高溫烘乾，30 cm 包覆上限也不適合更厚床墊。",
      bestFor: "在台灣選購雙人床包、重視親膚觸感與在地售後的人。",
      recommendation: "台灣綜合首選、親膚推薦：先量床墊厚度，含保潔墊後若超過約 30 cm，應改選深口袋款。",
      tags: ["Top Pick", "親膚推薦", "台灣製", "天絲"],
      score: 94,
    },
    {
      id: "bedsheet-hola-014366794",
      brand: "HOLA",
      model: "014366794",
      name: "查莉 100% 亞麻床包雙人 暮灰 150×186 cm",
      budget: "premium",
      type: "linen",
      variantFamily: "查莉100%亞麻床包",
      price: 3380,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/h5a/h98/12165812715550/000000000014366794-gallery-01-20240201145020631.jpg",
      buyUrl: "https://www.hola.com.tw/p/014366794",
      buyLabel: "HOLA 和樂台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人暮灰版本，SKU 014366794",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 亞麻",
        "織法／支數：活性印染；官方 exact SKU 頁未標示支數",
        "適用床墊：一般雙人床墊；床包四周鬆緊帶固定",
        "尺寸：寬 150 x 長 186 x 高 35 cm",
        "可包覆高度：約 35 cm",
        "認證／產地：BSMI M31849；葡萄牙製；第三方檢測涵蓋色牢度、起毛球、偶氮與甲醛",
        "清潔保養：40°C 以下水洗；不可漂白、低溫烘乾、110°C 以下熨燙、不可乾洗；分開洗並用中性洗劑",
        "重量：1.1 kg",
      ],
      focus: "天然亞麻透氣乾爽，35 cm 口袋也比多數一般床包更能容納厚床墊。",
      drawback: "售價高，亞麻初用觸感與自然皺褶不一定適合偏好平滑表面的人。",
      bestFor: "重視天然亞麻、乾爽觸感與厚床墊包覆空間的雙人床使用者。",
      recommendation: "天然材質候選：接受亞麻自然皺褶再買；先確認床墊加保潔墊後不超過約 35 cm。",
      tags: ["涼爽推薦", "天然亞麻", "35 cm 深口袋", "葡萄牙製"],
      score: 91,
    },
    {
      id: "bedsheet-ikea-50336953",
      brand: "IKEA",
      model: "503.369.53",
      name: "ULLVIDE 雙人床包 灰色 150×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "ULLVIDE",
      price: 799,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/040/0604097_PE681038_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/ullvide-art-50336953",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人灰色版本，SKU 503.369.53",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：85% 棉、15% 萊賽爾纖維",
        "織法／支數：密織；200 織數（787／平方公分）",
        "適用床墊：寬 150×長 200 cm 雙人床墊",
        "尺寸：寬 150 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "棉與萊賽爾混紡兼顧吸濕、透氣與相對平滑觸感。",
      drawback: "26 cm 包覆高度對厚床墊加保潔墊可能不足，官方也未列本體淨重。",
      bestFor: "使用 150×200 cm 床墊、希望棉感與天絲吸濕性平衡的人。",
      recommendation: "親膚混紡候選：先確認床墊長度確為 200 cm，並量含保潔墊後的總厚度。",
      tags: ["親膚推薦", "棉天絲混紡", "200 織數"],
      score: 90,
    },
    {
      id: "bedsheet-nitori-7518868",
      brand: "NITORI",
      model: "7518868",
      name: "N HOTEL 純棉多種厚度對應床包 WH 雙人",
      budget: "premium",
      type: "cotton",
      variantFamily: "N HOTEL",
      price: 899,
      image: "https://nitorimain.blob.core.windows.net/products/75/7518868_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/7518868",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；N HOTEL WH 雙人，SKU 7518868",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：條紋緞面織；官方 exact SKU 頁未標示支數",
        "適用床墊：一般雙人床墊；多種厚度對應",
        "尺寸：寬 150 x 深 186 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "純棉緞面條紋與約 38 cm 深口袋，兼顧觸感及厚床墊相容性。",
      drawback: "白色較需留意污漬，官方未標示支數與淨重。",
      bestFor: "雙人厚床墊、偏好飯店感純棉條紋的人。",
      recommendation: "厚床墊純棉候選：量測含保潔墊後總厚度，接近 38 cm 上限時預留鬆緊帶張力餘裕。",
      tags: ["親膚推薦", "純棉", "38 cm 深口袋", "飯店風"],
      score: 89,
    },
    {
      id: "bedsheet-ikea-00442673",
      brand: "IKEA",
      model: "004.426.73",
      name: "NATTJASMIN 雙人床包 深灰色 150×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "NATTJASMIN",
      price: 1199,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/689/0668967_PE714788_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/nattjasmin-art-00442673",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人深灰色版本，SKU 004.426.73",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：60% 棉、40% 萊賽爾纖維",
        "織法／支數：緞面織；310 織數（1220／平方公分）",
        "適用床墊：寬 150×長 200 cm 雙人床墊",
        "尺寸：寬 150 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "310 織數棉天絲緞面，偏向滑順親膚與吸濕的高階觸感。",
      drawback: "26 cm 口袋不適合超厚床墊，緞面也可能比一般平織更需留意勾紗。",
      bestFor: "想要滑順緞面、使用 150×200 cm 雙人床墊的人。",
      recommendation: "親膚緞面候選：避免與尖銳拉鍊同洗，並先確認床墊總厚度不超過約 26 cm。",
      tags: ["親膚推薦", "棉天絲緞面", "310 織數"],
      score: 89,
    },
    {
      id: "bedsheet-nitori-7518131",
      brand: "NITORI",
      model: "7518131",
      name: "POLY WASH 聚酯床包 GY 單人",
      budget: "value",
      type: "synthetic",
      variantFamily: "POLY WASH",
      price: 269,
      image: "https://nitorimain.blob.core.windows.net/products/75/7518131_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/7518131",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；POLY WASH GY 單人，SKU 7518131",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：聚酯纖維",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：一般單人床墊",
        "尺寸：寬 105 x 深 186 x 高 30 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "低價、快乾取向，適合作為單人床日常替換床包。",
      drawback: "聚酯觸感與透氣性偏好因人而異，規格頁未提供淨重。",
      bestFor: "租屋、宿舍或想先用低預算補齊替換床包的人。",
      recommendation: "入門替換候選：優先確認 105×186 cm 與約 30 cm 口袋是否吻合，不以低價取代材質偏好。",
      tags: ["入門價位", "快乾", "單人床"],
      score: 85,
    },
    {
      id: "bedsheet-ikea-30482460",
      brand: "IKEA",
      model: "304.824.60",
      name: "DVALA 單人床包 白色 90×200 cm",
      budget: "value",
      type: "cotton",
      variantFamily: "DVALA",
      price: 349,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/117/0811765_PE771834_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/dvala-art-30482460",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；單人白色版本，SKU 304.824.60",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：平織；152 織數（598／平方公分）",
        "適用床墊：寬 90×長 200 cm 單人床墊",
        "尺寸：寬 90 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "純棉、規格清楚且價格低，適合 90×200 cm 歐規單人床墊。",
      drawback: "90 cm 寬不是台灣常見 105 cm 單人尺寸，買錯會無法完整套合。",
      bestFor: "已確認床墊為 90×200 cm、想要平價純棉床包的人。",
      recommendation: "平價純棉候選：先量實床；台灣 105×186 cm 單人床墊不要直接套用這個 90×200 cm 版本。",
      tags: ["純棉", "入門價位", "90×200 cm"],
      score: 84,
    },
    {
      id: "bedsheet-nitori-7516608",
      brand: "NITORI",
      model: "7516608",
      name: "N FIT EVE2 伸縮床包 DBR 單人",
      budget: "value",
      type: "synthetic",
      variantFamily: "N FIT EVE2",
      price: 474,
      image: "https://nitorimain.blob.core.windows.net/products/75/7516608_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/7516608",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件伸縮床包；N FIT EVE2 DBR 單人，SKU 7516608",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：聚酯纖維、聚氨酯",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：日式床墊或一般單人彈簧床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 80 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：查不到（官方 exact SKU 頁未在可讀規格中標示洗滌方式）",
        "重量：查不到",
      ],
      focus: "伸縮與約 38 cm 包覆能力，可兼顧不同單人床墊厚度。",
      drawback: "材質比例與洗滌方式未完整標示，貼合度仍受床墊外形影響。",
      bestFor: "需要伸縮包覆、床墊厚度高於一般薄床包上限的單人床使用者。",
      recommendation: "深口袋伸縮候選：以官方適用床墊範圍判斷，不把 80×170 cm 成品尺寸誤當床墊尺寸。",
      tags: ["伸縮床包", "38 cm 深口袋", "快乾"],
      score: 84,
    },
    {
      id: "bedsheet-ikea-60482449",
      brand: "IKEA",
      model: "604.824.49",
      name: "DVALA 雙人床包 白色 150×200 cm",
      budget: "value",
      type: "cotton",
      variantFamily: "DVALA",
      price: 549,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/117/0811765_PE771834_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/dvala-art-60482449",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人白色版本，SKU 604.824.49",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：平織；152 織數（598／平方公分）",
        "適用床墊：寬 150×長 200 cm 雙人床墊",
        "尺寸：寬 150 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "平價純棉、150×200 cm 尺寸與 152 織數皆有官方 exact SKU 證據。",
      drawback: "200 cm 長與約 26 cm 口袋須實量，不等同台灣常見 150×186 cm 雙人床。",
      bestFor: "已確認使用 150×200 cm 雙人床墊、偏好純棉平織的人。",
      recommendation: "平價純棉候選：先量床墊長度與厚度；若是 186 cm 長床墊，優先選台規尺寸。",
      tags: ["純棉", "入門價位", "150×200 cm"],
      score: 83,
    },
    {
      id: "bedsheet-ikea-60482454",
      brand: "IKEA",
      model: "604.824.54",
      name: "DVALA 雙人加大床包 白色 180×200 cm",
      budget: "value",
      type: "cotton",
      variantFamily: "DVALA",
      price: 649,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/117/0811765_PE771834_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/dvala-art-60482454",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人加大白色版本，SKU 604.824.54",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：平織；152 織數（598／平方公分）",
        "適用床墊：寬 180×長 200 cm 雙人加大床墊",
        "尺寸：寬 180 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "180×200 cm 大尺寸仍維持平價純棉與可核對織數。",
      drawback: "180×200 cm 不等於所有台灣加大床規，且 26 cm 口袋對厚床墊可能不足。",
      bestFor: "實量為 180×200 cm、希望控制預算的雙人加大床墊。",
      recommendation: "大尺寸平價候選：寬、長、厚三項都要實量，不能只看「雙人加大」名稱。",
      tags: ["純棉", "入門價位", "180×200 cm"],
      score: 82,
    },
    {
      id: "bedsheet-nitori-7518718",
      brand: "NITORI",
      model: "7518718",
      name: "WASH 水洗純棉多種厚度對應床包 DGY 單人",
      budget: "value",
      type: "cotton",
      variantFamily: "水洗純棉 WASH",
      price: 599,
      image: "https://nitorimain.blob.core.windows.net/products/75/7518718_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/7518718",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；水洗純棉 WASH DGY 單人，SKU 7518718",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：水洗加工；約 106 織／平方英吋",
        "適用床墊：一般 105×186 cm 或日式 90×186 cm 單人床墊",
        "尺寸：寬 105 x 深 186 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "水洗純棉與約 38 cm 深口袋，兼顧台灣一般單人床與厚床墊。",
      drawback: "水洗皺感屬風格取向，官方未標示淨重。",
      bestFor: "想要水洗棉觸感、台規單人床尺寸與較深包覆空間的人。",
      recommendation: "平價厚床墊候選：單人床寬度仍須確認是 105 cm 或 90 cm，並量含保潔墊後總厚度。",
      tags: ["純棉", "水洗棉", "38 cm 深口袋"],
      score: 86,
    },
    {
      id: "bedsheet-nitori-2115100119564",
      brand: "NITORI",
      model: "2115100119564",
      name: "竹纖緞面多種厚度對應床包 GY S2611 單人",
      budget: "mid",
      type: "other_natural",
      variantFamily: "竹纖緞面 S2611",
      price: 699,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100119564_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100119564",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；竹纖緞面 GY S2611 單人，SKU 2115100119564",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 竹纖維",
        "織法／支數：緞面織；官方 exact SKU 頁未標示支數",
        "適用床墊：一般單人床墊；多種厚度對應",
        "尺寸：寬 105 x 深 188 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "竹纖維緞面兼顧滑順與深口袋，適合想避開一般棉或聚酯表面的人。",
      drawback: "竹纖維的耐用與觸感需依實品判斷，官方未標示支數與淨重。",
      bestFor: "偏好竹纖維緞面、又需要約 38 cm 包覆高度的單人床。",
      recommendation: "涼爽材質候選：避免高摩擦混洗，並依 105×188 cm 成品規格與床墊實量判斷。",
      tags: ["涼爽推薦", "竹纖維", "緞面", "38 cm 深口袋"],
      score: 87,
    },
    {
      id: "bedsheet-ikea-20458856",
      brand: "IKEA",
      model: "204.588.56",
      name: "HÖSTVÄDD 單人加寬涼感床包 120×200 cm",
      budget: "mid",
      type: "synthetic",
      variantFamily: "HÖSTVÄDD",
      price: 549,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/836/0883619_PE647061_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/hostvadd-art-20458856",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件涼感床包；120×200 cm 版本，SKU 204.588.56",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：表面 50% 嫘縈、50% 尼龍；側面 100% 再生聚酯纖維",
        "織法／支數：特殊涼感針織；官方 exact SKU 頁未標示支數",
        "適用床墊：寬 120×長 200 cm 床墊",
        "尺寸：寬 120 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：40°C 機洗；不可漂白；80°C 一般烘乾；110°C 以下熨燙且不可蒸氣；不可乾洗",
        "重量：查不到",
      ],
      focus: "涼感針織表面，適合炎熱季節與容易悶熱的睡眠環境。",
      drawback: "120×200 cm 尺寸不常見，26 cm 口袋與人造纖維觸感都應先確認。",
      bestFor: "床墊確為 120×200 cm、夏天在意接觸涼感的人。",
      recommendation: "涼爽推薦：先量床墊尺寸與厚度；涼感表面不能取代室內通風與適當空調。",
      tags: ["涼爽推薦", "涼感針織", "120×200 cm"],
      score: 87,
    },
    {
      id: "bedsheet-ikea-00458857",
      brand: "IKEA",
      model: "004.588.57",
      name: "HÖSTVÄDD 雙人涼感床包 150×200 cm",
      budget: "mid",
      type: "synthetic",
      variantFamily: "HÖSTVÄDD",
      price: 649,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/836/0883619_PE647061_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/hostvadd-art-00458857",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件涼感床包；150×200 cm 版本，SKU 004.588.57",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：表面 50% 嫘縈、50% 尼龍；側面 100% 再生聚酯纖維",
        "織法／支數：特殊涼感針織；官方 exact SKU 頁未標示支數",
        "適用床墊：寬 150×長 200 cm 雙人床墊",
        "尺寸：寬 150 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：40°C 機洗；不可漂白；80°C 一般烘乾；110°C 以下熨燙且不可蒸氣；不可乾洗",
        "重量：查不到",
      ],
      focus: "150×200 cm 雙人尺寸搭配涼感針織，定位清楚。",
      drawback: "不是台灣常見 150×186 cm 長度，且包覆上限約 26 cm。",
      bestFor: "使用 150×200 cm 床墊、夏季容易悶熱的雙人床。",
      recommendation: "涼爽推薦：先核對 200 cm 長度；若床墊較厚或加保潔墊，26 cm 口袋可能不足。",
      tags: ["涼爽推薦", "涼感針織", "150×200 cm"],
      score: 86,
    },
    {
      id: "bedsheet-ikea-80458858",
      brand: "IKEA",
      model: "804.588.58",
      name: "HÖSTVÄDD 雙人加大涼感床包 180×200 cm",
      budget: "mid",
      type: "synthetic",
      variantFamily: "HÖSTVÄDD",
      price: 749,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/836/0883619_PE647061_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/hostvadd-art-80458858",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件涼感床包；180×200 cm 版本，SKU 804.588.58",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：表面 50% 嫘縈、50% 尼龍；側面 100% 再生聚酯纖維",
        "織法／支數：特殊涼感針織；官方 exact SKU 頁未標示支數",
        "適用床墊：寬 180×長 200 cm 雙人加大床墊",
        "尺寸：寬 180 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：40°C 機洗；不可漂白；80°C 一般烘乾；110°C 以下熨燙且不可蒸氣；不可乾洗",
        "重量：查不到",
      ],
      focus: "大尺寸涼感針織，能覆蓋 180×200 cm 雙人加大床墊。",
      drawback: "尺寸與台灣加大床規不一定一致，厚床墊也可能超過 26 cm 口袋。",
      bestFor: "床墊實量 180×200 cm、需要夏季接觸涼感的人。",
      recommendation: "大床涼爽候選：確認尺寸後再買，並保留空調、除濕與清洗輪替的整體睡眠方案。",
      tags: ["涼爽推薦", "涼感針織", "180×200 cm"],
      score: 86,
    },
    {
      id: "bedsheet-nitori-2115100107202",
      brand: "NITORI",
      model: "2115100107202",
      name: "N FIT FT05 COTTON 伸縮床包 GY 單人",
      budget: "mid",
      type: "cotton",
      variantFamily: "N FIT FT05 COTTON",
      price: 799,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100107202_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100107202",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件伸縮床包；N FIT FT05 COTTON GY 單人，SKU 2115100107202",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：95% 棉、5% 聚氨酯",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：日式床墊或一般單人彈簧床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 80 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "以棉為主的伸縮針織，兼顧貼合與約 38 cm 深口袋。",
      drawback: "含聚氨酯需留意高溫與長期彈性衰退，官方未標示淨重。",
      bestFor: "想要棉感、又需要伸縮貼合厚單人床墊的人。",
      recommendation: "棉質伸縮候選：依適用床墊說明選購，不把伸縮成品尺寸直接當成床墊尺寸。",
      tags: ["親膚推薦", "棉質伸縮", "38 cm 深口袋"],
      score: 88,
    },
    {
      id: "bedsheet-nitori-2115100006123",
      brand: "NITORI",
      model: "2115100006123",
      name: "PT30 BOTANICAL 純棉多種厚度對應床包 RO 單人",
      budget: "mid",
      type: "cotton",
      variantFamily: "PT30 BOTANICAL",
      price: 719,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100006123_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100006123",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；PT30 BOTANICAL RO 單人，SKU 2115100006123",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：一般或日式單人床墊；多種厚度對應",
        "尺寸：寬 105 x 深 186 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：BSMI M32501；印度製",
        "清潔保養：裝洗衣袋機洗；與其他衣物分洗；不可使用含氯漂白劑，整形後晾乾",
        "重量：查不到",
      ],
      focus: "100% 棉、印度製與約 38 cm 包覆上限均有 exact SKU 證據；相較 WASH 款，WASH 另有水洗加工與約106織的實質表面規格，本款不以花色單獨計數。",
      drawback: "花色搭配偏好主觀，官方頁仍未列織法、支數與淨重。",
      bestFor: "希望一般純棉表面、並需要較深單人床口袋的人。",
      recommendation: "一般純棉候選：與另具水洗加工及約 106 織規格的 WASH 款分開評估；本筆不以 BOTANICAL 花色作為分列理由。",
      tags: ["純棉", "38 cm 深口袋", "一般織面"],
      score: 85,
    },
    {
      id: "bedsheet-nitori-7518634",
      brand: "NITORI",
      model: "7518634",
      name: "天絲塞內加爾床包 單人 105×186 cm",
      budget: "mid",
      type: "lyocell",
      variantFamily: "天絲塞內加爾",
      price: 699,
      image: "https://nitorimain.blob.core.windows.net/products/75/7518634_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/7518634",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；天絲塞內加爾單人，SKU 7518634",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：萊賽爾纖維、聚酯纖維",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：一般單人床墊",
        "尺寸：寬 105 x 深 186 x 高 27 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：查不到（官方 exact SKU 頁未在可讀規格中標示洗滌方式）",
        "重量：查不到",
      ],
      focus: "台規單人尺寸的萊賽爾混紡，適合想用中階價格嘗試滑順觸感。",
      drawback: "官方未列完整材質比例、洗滌方式與淨重。",
      bestFor: "使用 105×186 cm 單人床墊、想嘗試天絲混紡的人。",
      recommendation: "中階親膚候選：先確認材質比例與洗標是否符合個人需求，再以約 30 cm 上限核對厚度。",
      tags: ["親膚推薦", "天絲混紡", "台規單人"],
      score: 84,
    },
    {
      id: "bedsheet-nitori-2115100004365",
      brand: "NITORI",
      model: "2115100004365",
      name: "N FIT FT01 PREMIUM 莫代爾伸縮床包 GY 單人",
      budget: "mid",
      type: "other_natural",
      variantFamily: "N FIT FT01 PREMIUM",
      price: 949,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100004365_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100004365",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件伸縮床包；N FIT FT01 PREMIUM GY 單人，SKU 2115100004365",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：94% 莫代爾纖維、6% 聚酯纖維",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：日式床墊或一般單人彈簧床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 80 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "高比例莫代爾帶來柔滑觸感，伸縮設計與深口袋也有實用性。",
      drawback: "含聚酯且價格高於基本款，長期伸縮耐用度需依實際使用判斷。",
      bestFor: "偏好莫代爾柔滑感、需要厚單人床墊伸縮包覆的人。",
      recommendation: "柔滑伸縮候選：避免高溫洗烘，並依官方適用床墊與約 38 cm 上限選購。",
      tags: ["親膚推薦", "莫代爾", "伸縮床包", "38 cm 深口袋"],
      score: 88,
    },
    {
      id: "bedsheet-nitori-2115100006703",
      brand: "NITORI",
      model: "2115100006703",
      name: "N FIT PLAIN 伸縮床包 IV 雙人",
      budget: "mid",
      type: "synthetic",
      variantFamily: "N FIT PLAIN",
      price: 719,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100006703_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100006703",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件伸縮床包；N FIT PLAIN IV 雙人，SKU 2115100006703",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：95% 聚酯纖維、5% 聚氨酯",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：一般或日式雙人床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 125 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "雙人伸縮床包可減少鋪床皺褶，約 38 cm 深口袋對厚床墊友善。",
      drawback: "聚酯為主的觸感與透氣性偏好因人而異，伸縮性也不代表所有床墊都通用。",
      bestFor: "希望快速鋪床、需要雙人厚床墊伸縮包覆的人。",
      recommendation: "便利伸縮候選：確認床墊外形與厚度，再依官方適用範圍選購，不以成品尺寸自行外推。",
      tags: ["伸縮床包", "38 cm 深口袋", "快乾"],
      score: 86,
    },
    {
      id: "bedsheet-ikea-40335548",
      brand: "IKEA",
      model: "403.355.48",
      name: "ULLVIDE 單人床包 灰色 90×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "ULLVIDE",
      price: 549,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/040/0604097_PE681038_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/ullvide-art-40335548",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；單人灰色版本，SKU 403.355.48",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：85% 棉、15% 萊賽爾纖維",
        "織法／支數：密織；200 織數（787／平方公分）",
        "適用床墊：寬 90×長 200 cm 單人床墊",
        "尺寸：寬 90 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：0.48 kg",
      ],
      focus: "棉天絲混紡、200 織數與 0.48 kg 淨重都有 exact SKU 官方證據。",
      drawback: "90×200 cm 並非台灣常見 105×186 cm 單人尺寸，且口袋僅約 26 cm。",
      bestFor: "床墊確為 90×200 cm、希望較平滑吸濕表面的人。",
      recommendation: "親膚單人候選：尺寸不合就不買；這筆淨重證據只適用 403.355.48，不跨套到同系列其他尺寸。",
      tags: ["親膚推薦", "棉天絲混紡", "200 織數", "90×200 cm"],
      score: 88,
    },
    {
      id: "bedsheet-ikea-90342773",
      brand: "IKEA",
      model: "903.427.73",
      name: "ULLVIDE 雙人加大床包 深藍色 180×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "ULLVIDE",
      price: 899,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/040/0604098_PE681037_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/ullvide-art-90342773",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人加大深藍色版本，SKU 903.427.73",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：85% 棉、15% 萊賽爾纖維",
        "織法／支數：密織；200 織數（787／平方公分）",
        "適用床墊：寬 180×長 200 cm 雙人加大床墊",
        "尺寸：寬 180 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "180×200 cm 大尺寸棉天絲混紡，規格與 exact SKU 清楚。",
      drawback: "深藍色褪色與 26 cm 口袋限制都需留意，官方未列淨重。",
      bestFor: "床墊實量 180×200 cm、希望大尺寸仍有吸濕滑順表面的人。",
      recommendation: "大床親膚候選：深色分開洗，並先確認床墊加保潔墊後不超過約 26 cm。",
      tags: ["親膚推薦", "棉天絲混紡", "180×200 cm"],
      score: 88,
    },
    {
      id: "bedsheet-ikea-00442668",
      brand: "IKEA",
      model: "004.426.68",
      name: "NATTJASMIN 單人加寬床包 深灰色 120×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "NATTJASMIN",
      price: 999,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/689/0668967_PE714788_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/nattjasmin-art-00442668",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；120×200 cm 深灰色版本，SKU 004.426.68",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：60% 棉、40% 萊賽爾纖維",
        "織法／支數：緞面織；310 織數（1220／平方公分）",
        "適用床墊：寬 120×長 200 cm 床墊",
        "尺寸：寬 120 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "310 織數棉天絲緞面，適合 120×200 cm 特定床規。",
      drawback: "尺寸不普遍，且緞面與約 26 cm 口袋都需配合使用習慣。",
      bestFor: "已確認床墊為 120×200 cm、偏好細緻緞面的人。",
      recommendation: "高織數親膚候選：先量尺寸；避免只憑「單人加寬」名稱推定相容。",
      tags: ["親膚推薦", "棉天絲緞面", "310 織數", "120×200 cm"],
      score: 87,
    },
    {
      id: "bedsheet-ikea-90442678",
      brand: "IKEA",
      model: "904.426.78",
      name: "NATTJASMIN 雙人加大床包 深灰色 180×200 cm",
      budget: "premium",
      type: "lyocell",
      variantFamily: "NATTJASMIN",
      price: 1299,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/689/0668967_PE714788_S2.webp",
      buyUrl: "https://www.ikea.com.tw/zh/products/bedlinen/sheets-and-pillow-cases/nattjasmin-art-90442678",
      buyLabel: "IKEA 台灣官方商城",
      specs: [
        "類型：成人床用單件床包；雙人加大深灰色版本，SKU 904.426.78",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：60% 棉、40% 萊賽爾纖維",
        "織法／支數：緞面織；310 織數（1220／平方公分）",
        "適用床墊：寬 180×長 200 cm 雙人加大床墊",
        "尺寸：寬 180 x 長 200 cm",
        "可包覆高度：約 26 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：60°C 機洗；不可漂白；80°C 一般烘乾；200°C 以下熨燙；不可乾洗",
        "重量：查不到",
      ],
      focus: "大尺寸 310 織數棉天絲緞面，適合追求滑順觸感的 180×200 cm 床。",
      drawback: "售價較高、深色需分洗，且口袋僅約 26 cm。",
      bestFor: "床墊實量 180×200 cm、重視緞面滑順與吸濕的人。",
      recommendation: "大床緞面候選：量好床墊厚度，並避免與粗糙五金或拉鍊衣物混洗。",
      tags: ["親膚推薦", "棉天絲緞面", "310 織數", "180×200 cm"],
      score: 88,
    },
    {
      id: "bedsheet-nitori-2115100027623",
      brand: "NITORI",
      model: "2115100027623",
      name: "ORCHID 100% 天絲床包 單人",
      budget: "premium",
      type: "lyocell",
      variantFamily: "天絲 ORCHID",
      price: 899,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100027623_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100027623",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；天絲 ORCHID 單人，SKU 2115100027623",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 萊賽爾纖維（天絲）",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：一般單人床墊",
        "尺寸：寬 105 x 深 186 x 高 1 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗；不可漂白、不可烘乾",
        "重量：查不到",
      ],
      focus: "100% 萊賽爾與台規單人尺寸，定位在滑順吸濕的親膚表面。",
      drawback: "官方成品尺寸列高 1 cm，另列適用床墊約 30 cm 上限；兩者不可混用。",
      bestFor: "使用台規單人床、希望 100% 天絲觸感的人。",
      recommendation: "親膚推薦：以約 30 cm 適用厚度選床墊，不將官方成品高 1 cm 誤解成包覆高度。",
      tags: ["親膚推薦", "100% 天絲", "台規單人"],
      score: 89,
    },
    {
      id: "bedsheet-nitori-2115100123042",
      brand: "NITORI",
      model: "2115100123042",
      name: "精梳棉純棉床包 LGR 單人",
      budget: "mid",
      type: "cotton",
      variantFamily: "精梳棉床包",
      price: 899,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100123042_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100123042",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；精梳棉 LGR 單人，SKU 2115100123042",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 棉",
        "織法／支數：精梳棉；官方 exact SKU 頁未標示支數",
        "適用床墊：一般單人床墊",
        "尺寸：寬 105 x 深 186 x 高 27 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "100% 精梳棉與台規 105×186 cm 尺寸，適合偏好純棉基本盤的人。",
      drawback: "官方未標示支數、產地與淨重，30 cm 口袋也非深口袋級。",
      bestFor: "台規單人床、希望使用精梳純棉的人。",
      recommendation: "親膚純棉候選：先核對床墊厚度，再依洗標保養；不要只用精梳棉名稱推定支數。",
      tags: ["親膚推薦", "精梳棉", "台規單人"],
      score: 87,
    },
    {
      id: "bedsheet-nitori-2115100119403",
      brand: "NITORI",
      model: "2115100119403",
      name: "N FIT N COOL 極冷 GY 26NC-04 接觸涼感伸縮床包 單人",
      budget: "mid",
      type: "synthetic",
      variantFamily: "N FIT N COOL 極冷 26NC-04",
      price: 899,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100119403_01.jpg",
      buyUrl: "https://24h.pchome.com.tw/prod/DQCI0J-A900JTB2E",
      buyLabel: "PChome 24h NITORI 宜得利新品頁",
      specs: [
        "類型：成人床用單件接觸涼感伸縮床包；N FIT N COOL 極冷 GY 26NC-04 單人，SKU 2115100119403",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：75% 尼龍、13% 聚氨酯、12% 聚酯纖維",
        "織法／支數：接觸涼感伸縮布料；官方與通路 exact SKU 頁未標示支數",
        "適用床墊：寬 75–108 x 深 170–210 cm 的日式或一般床墊",
        "尺寸：寬 80 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：BSMI M32501；中國製",
        "清潔保養：裝洗衣袋機洗；潮濕或摩擦可能褪色、染色，勿長時間直接接觸牆面",
        "重量：查不到",
      ],
      focus: "N COOL 極冷接觸涼感布料、抗菌防臭與除臭加工，並以伸縮設計涵蓋小型單人至一般單人床墊。",
      drawback: "接觸涼感受室溫與個人體感影響，複合纖維也不等同純棉或天絲觸感。",
      bestFor: "單人床、夏季容易悶熱且需要約 38 cm 包覆上限的人。",
      recommendation: "涼爽單人推薦：PChome exact 原廠編號頁可直接還原 SKU 2115100119403；購買前仍須核對 75–108×170–210 cm 適用範圍。",
      tags: ["涼爽推薦", "N COOL 極冷", "抗菌防臭", "38 cm 深口袋"],
      score: 86,
    },
    {
      id: "bedsheet-nitori-2115100027647",
      brand: "NITORI",
      model: "2115100027647",
      name: "ORCHID 100% 天絲床包 雙人加大",
      budget: "premium",
      type: "lyocell",
      variantFamily: "天絲 ORCHID",
      price: 1190,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100027647_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100027647",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件床包；天絲 ORCHID 雙人加大，SKU 2115100027647",
        "組合內容：床包 1 件；不含被套、棉被與枕套",
        "材質：100% 萊賽爾纖維（天絲）",
        "織法／支數：官方 exact SKU 頁未標示織法或支數",
        "適用床墊：寬 180×長 186 cm 一般或日式雙人加大床墊",
        "尺寸：寬 180 x 深 186 x 高 1 cm",
        "可包覆高度：約 30 cm",
        "認證／產地：BSMI M32501；台灣製",
        "清潔保養：裝洗衣袋機洗；與其他衣物分洗；不可漂白、不可烘乾，整形後晾乾",
        "重量：查不到",
      ],
      focus: "100% 天絲與台規 180×186 cm 雙人加大尺寸，為同系列可獨立購買的官方尺寸 SKU。",
      drawback: "約 30 cm 口袋不適合超厚床墊；官方未標示本體淨重。",
      bestFor: "台規雙人加大床、希望 100% 天絲與台灣製造的人。",
      recommendation: "親膚加大候選：量好 180×186 cm 與總厚度，固定使用 exact SKU 2115100027647 的價格與證據。",
      tags: ["親膚推薦", "100% 天絲", "台灣製", "台規雙人加大"],
      score: 88,
    },
    {
      id: "bedsheet-nitori-2115100053394",
      brand: "NITORI",
      model: "2115100053394",
      name: "N COOL WSP D2518 極致涼感伸縮床包 BL 雙人加大",
      budget: "premium",
      type: "synthetic",
      variantFamily: "N COOL WSP D2518",
      price: 1043,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100053394_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100053394",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件極致涼感伸縮床包；BL D2518 雙人加大，SKU 2115100053394",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：90% 尼龍、10% 聚氨酯；PCM 涼感塗層",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：一般或日式雙人加大床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 140 x 深 170 x 高 40 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "PCM 塗層、尼龍表面與伸縮深口袋，定位在炎熱季節的大床使用。",
      drawback: "接觸涼感會隨環境與體感變化，塗層耐久也需遵守洗標。",
      bestFor: "雙人加大床、夏季容易悶熱且需要伸縮深口袋的人。",
      recommendation: "涼爽推薦：涼感不能取代空調；避免高溫洗烘並依約 38 cm 包覆上限選購。",
      tags: ["涼爽推薦", "極致涼感", "PCM", "38 cm 深口袋"],
      score: 89,
    },
    {
      id: "bedsheet-nitori-2115100053264",
      brand: "NITORI",
      model: "2115100053264",
      name: "N COOL SP 25NC-11 進階涼感伸縮床包 BL 雙人加大",
      budget: "mid",
      type: "synthetic",
      variantFamily: "N COOL SP 25NC-11",
      price: 699,
      image: "https://nitorimain.blob.core.windows.net/products/21/2115100053264_01.jpg",
      buyUrl: "https://www.nitori-net.tw/product/2115100053264",
      buyLabel: "NITORI 宜得利台灣官方商城",
      specs: [
        "類型：成人床用單件進階涼感伸縮床包；BL 25NC-11 雙人加大，SKU 2115100053264",
        "組合內容：伸縮床包 1 件；不含被套、棉被與枕套",
        "材質：46% 尼龍、46% 聚乙烯纖維、5% 聚酯纖維、3% 聚氨酯",
        "織法／支數：伸縮針織；官方 exact SKU 頁未標示支數",
        "適用床墊：一般或日式雙人加大床墊；商品尺寸小於適用床墊屬伸縮設計",
        "尺寸：寬 140 x 深 180 x 高 35 cm",
        "可包覆高度：約 38 cm",
        "認證／產地：官方 exact SKU 頁未標示認證或產地",
        "清潔保養：裝洗衣袋機洗",
        "重量：查不到",
      ],
      focus: "多纖維涼感表面與伸縮設計，價格低於 WSP 等級。",
      drawback: "複合纖維觸感、耐用與涼感持續性需依實際環境判斷。",
      bestFor: "雙人加大床、想用中階預算取得涼感與深口袋的人。",
      recommendation: "涼爽推薦：先比較 WSP 與 SP 觸感，不用系列等級名稱替代實際試睡與洗滌評估。",
      tags: ["涼爽推薦", "進階涼感", "伸縮床包", "38 cm 深口袋"],
      score: 87,
    },
  ].map((product, index) => {
    const issueCheckedSources = issueSources(product.model);
    return {
      id: product.id,
      category: "bedsheet",
      rank: index + 1,
      budget: product.budget,
      channel: "tw",
      brand: product.brand,
      model: product.model,
      name: product.name,
      type: product.type,
      variantFamily: product.variantFamily,
      topPick: Boolean(product.topPick),
      price: {
        currency: "TWD",
        amount: product.price,
        converted: product.price,
        basis: "retailer_current",
        confidence: `${CHECKED_AT} 以 Chrome 核對 ${product.buyLabel} exact SKU ${product.model} 新品頁所選版本公開現價；未扣會員、信用卡、點數、贈品或套裝差異。`,
      },
      installation: {
        status: "not_stated",
        note: "成人床用成品床包不需到府安裝；購買前需自行量測床墊寬、長、厚度及加上保潔墊後的總高度。",
      },
      image: product.image,
      buyUrl: product.buyUrl,
      buyLabel: product.buyLabel,
      specs: product.specs,
      description: `${product.focus} 本筆固定為 ${product.model} 與名稱所列尺寸，不以同系列顏色、花色、件數或其他尺寸跨版套用價格與證據。`,
      pros: [
        `${product.buyLabel} exact SKU 新品頁可核對現價、購買版本與圖片`,
        product.focus,
        `尺寸與包覆高度分列，避免把床包成品高度當成床墊適用厚度`,
      ],
      cons: [
        product.drawback,
        product.specs.at(-1) === "重量：查不到" ? "官方 exact SKU 頁未提供可確認的本體淨重" : "仍須依床墊實量與個人材質觸感決定",
        "未查得同一 exact SKU 可公開重現的上市日與歷史最低價",
      ],
      bestFor: product.bestFor,
      recommendation: product.recommendation,
      releaseDate: "找不到",
      historicalLow: {
        status: "not_found",
        amount: null,
        currency: "TWD",
        converted: null,
        sourceUrl: "",
        sourceTitle: "",
        evidenceSnippet: "",
        sourceKind: "not_found",
        confidence: "not_found",
        checkedAt: CHECKED_AT,
        note: `${CHECKED_AT} 以 Chrome 核對 exact SKU ${product.model} 的 ${product.buyLabel} 現售頁，並執行 exact-model 上市／發售／開賣／launch／release／史低／價格歷史查詢；未取得可公開重現、具日期且同一版本的可信新品歷史最低價，現價不倒推為史低。`,
      },
      issueResearch: {
        status: "no_common_issue",
        checkedAt: CHECKED_AT,
        summary: NO_COMMON_ISSUE,
        issues: [],
        checkedSources: issueCheckedSources,
      },
      score: product.score,
      voltage: "非電器，不需供電。",
      warranty: warrantyByBrand[product.brand],
      tags: product.tags,
    };
  });

  dashboard.registerProducts("bedsheet", products);
})();
