(() => {
  const dashboard = globalThis.applianceDashboard;
  if (!dashboard || typeof dashboard.registerProducts !== "function") {
    throw new Error("appliance dashboard registry is not ready");
  }

  const checkedAt = "2026-09-01";
  const issueSources = (model) => [
    {
      platform: "Reddit",
      query: `site:reddit.com "${model}" problem OR issue`,
      targetHost: "reddit.com",
      queryUrl: `https://www.bing.com/search?q=${encodeURIComponent(`site:reddit.com "${model}" problem OR issue`)}`,
    },
    {
      platform: "Mobile01",
      query: `site:mobile01.com "${model}" 問題 OR 災情`,
      targetHost: "mobile01.com",
      queryUrl: `https://www.bing.com/search?q=${encodeURIComponent(`site:mobile01.com "${model}" 問題 OR 災情`)}`,
    },
  ];
  const makeProduct = ({ price, url, label, score, topPick = false, ...item }, index) => ({
    ...item,
    rank: index + 1,
    budget: item.budget,
    channel: "tw",
    topPick,
    price: {
      currency: "TWD",
      amount: price,
      converted: price,
      basis: "retailer_current",
      confidence: `${checkedAt} 以 Chrome 核對 exact SKU 台灣新品公開售價；不扣會員、信用卡、點數、滿額或贈品優惠。`,
    },
    installation: {
      status: "not_stated",
      note: "完整被芯／成品被不需施工；購買前仍須核對被套、床型尺寸、收納空間與清潔條件。",
    },
    buyUrl: url,
    buyLabel: label,
    releaseDate: "找不到",
    historicalLow: {
      status: "not_found",
      amount: null,
      currency: "TWD",
      converted: null,
      sourceUrl: "",
      sourceTitle: "",
      evidenceSnippet: "",
      sourceKind: "not_found",
      confidence: "not_found",
      checkedAt,
      note: `${checkedAt} 以 exact SKU「${item.model}」分別查 BigGo 與 FindPrice；未取得同尺寸、同版本、具日期且可公開重現的可信新品史低，不以本次現價或跨版本價格推定。`,
    },
    issueResearch: {
      status: "no_common_issue",
      checkedAt,
      summary: "截至查核日，查無達門檻的集中負評／災情",
      issues: [],
      checkedSources: issueSources(item.model),
    },
    score: score ?? Math.max(70, 94 - index),
    voltage: "非電器，不需供電；非電熱毯。",
  });

  const items = [
    {
      id: "comforter-hola-wool-016788505",
      category: "comforter",
      brand: "HOLA",
      model: "016788505",
      variantFamily: "HOLA 100%可水洗法國羊毛防蟎冬被",
      name: "100%可水洗法國羊毛防蟎冬被雙人（016788505）",
      type: "wool",
      budget: "mid",
      topPick: true,
      price: 2480,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/hcd/hc8/12330913431582/000000000016788505-gallery-01-20241029161043256.jpg",
      url: "https://www.momoshop.com.tw/TP/TP0006553/goodsDetail/TP00065530008496",
      label: "momo HOLA 官方店",
      specs: [
        "類型：羊毛冬被；雙人；完整被芯",
        "組合內容：冬被 1 件",
        "表布材質：100% 聚酯纖維",
        "填充材質：100% 法國羊毛",
        "填充比例／蓬鬆度：羊毛 100%；蓬鬆度不適用",
        "適用季節／保暖性：冬季；原頁建議約 16–18°C 室溫",
        "尺寸：長 210 x 寬 180 x 高 1 cm",
        "填充重量：1.4 kg",
        "重量：2.45 kg",
        "認證／產地：Woolmark Pure New Wool、TTRI 物理防蟎；中國製",
        "清潔保養：低溫柔洗或專業乾洗；不可漂白、烘乾、熨燙",
      ],
      description: "台灣可信通路、雙人常用尺寸、完整尺寸與淨重證據都可回查的羊毛冬被。羊毛填充 1.4 kg，適合希望兼顧保暖、可水洗標示與本地售後者。",
      pros: ["台灣 HOLA 官方店 exact 貨號", "100% 法國羊毛且分列填充與整件重量", "雙人 180 × 210 cm、可低溫柔洗"],
      cons: ["表布為聚酯纖維而非棉", "2.45 kg 整件重量較有壓感", "清潔仍須遵守低溫柔洗限制"],
      bestFor: "冬季怕冷、想買台灣可追溯售後與雙人標準尺寸羊毛被的家庭。",
      recommendation: "台灣 Top Pick、冬季保暖推薦：先確認洗衣機容量與低溫柔洗行程；對羊毛或聚酯表布觸感敏感者先試觸。",
      warranty: "HOLA 台灣官方店新品，可由台灣客服與門市協助；原頁未列獨立年限保固，拆封寢具退換限制依通路規範。",
      tags: ["台灣 Top Pick", "冬季保暖推薦", "羊毛", "雙人"],
    },
    {
      id: "comforter-ikea-skogsfraken-70618640",
      category: "comforter",
      brand: "IKEA",
      model: "706.186.40",
      variantFamily: "SKOGSFRÄKEN 四季被",
      name: "SKOGSFRÄKEN 四季被 150×200 cm（706.186.40）",
      type: "synthetic",
      budget: "mid",
      price: 2799,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/093/1409319_PE972199_S4.webp",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/skogsfraken-art-70618640",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：化纖／萊賽爾混填四季被；單人；固定二件式",
        "組合內容：涼被 1 件＋暖被 1 件，可用固定扣結合",
        "表布材質：60% 再生聚酯纖維、40% 萊賽爾纖維",
        "填充材質：60% 再生聚酯中空纖維、40% 萊賽爾纖維",
        "填充比例／蓬鬆度：聚酯 60%／萊賽爾 40%；蓬鬆度未標示",
        "適用季節／保暖性：四季；4＋7.5 TOG，可分用或扣合",
        "尺寸：長 200 x 寬 150 cm",
        "填充重量：涼被 0.51 kg；暖被 0.96 kg",
        "重量：涼被 1.39 kg；暖被 1.84 kg",
        "認證／產地：EN ISO 12952-1 與 CAN/CGSB 4.2 No.27.5 耐燃測試；產地原頁未標示",
        "清潔保養：60°C 機洗；其餘程序依 IKEA 原頁洗標",
      ],
      description: "一組內含涼被與暖被，兩件可用固定扣合併，從換季到寒夜都能調整。來源將兩件的填充重量與整件重量分列，本站不自行合計。",
      pros: ["官方固定二件式而非促銷套裝", "4＋7.5 TOG 可依季節組合", "分件尺寸與重量證據完整"],
      cons: ["扣合後整體較厚重", "單人 150 cm 寬不適合雙人共蓋", "聚酯比例仍高"],
      bestFor: "希望一組覆蓋冷氣房、換季與冬季，且重視可機洗的單人使用者。",
      recommendation: "四季推薦：依室溫分開使用，寒冷時再扣合；收納時保持兩件完全乾燥。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["四季推薦", "二件式", "可機洗", "單人"],
    },
    {
      id: "comforter-ikea-smasporre-10458588",
      category: "comforter",
      brand: "IKEA",
      model: "104.585.88",
      variantFamily: "SMÅSPORRE",
      name: "SMÅSPORRE 四季被 150×200 cm（104.585.88）",
      type: "synthetic",
      budget: "value",
      price: 1299,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/883/0788307_PE763566_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/smasporre-art-10458588",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：化纖四季被；單人；固定二件式",
        "組合內容：涼被 1 件＋暖被 1 件，可用固定扣結合",
        "表布材質：65% 再生聚酯纖維、35% 棉",
        "填充材質：100% 再生聚酯中空纖維",
        "填充比例／蓬鬆度：再生聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：四季；4＋7.5 TOG，可分用或扣合",
        "尺寸：長 200 x 寬 150 cm",
        "填充重量：涼被 0.45 kg；暖被 0.84 kg",
        "重量：涼被 1.08 kg；暖被 1.47 kg",
        "認證／產地：IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗、最高 80°C 烘乾；不可漂白、熨燙、乾洗",
      ],
      description: "價位較低的官方二件式四季被，分開是涼／暖兩種保暖度，扣合後應付更冷環境。每件重量均按官方尺寸表保留。",
      pros: ["一組三種保暖組合", "60°C 可機洗", "價位低且 exact article 可回查"],
      cons: ["填充為聚酯纖維", "扣合與晾乾占空間", "產地未在原頁標示"],
      bestFor: "租屋、學生或希望以一組覆蓋多季的單人使用者。",
      recommendation: "入門四季被：依室溫拆分，不需寒冷時避免長期扣合造成過熱。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["四季推薦", "高 CP 值", "二件式", "單人"],
    },
    {
      id: "comforter-ikea-smasporre-00458584",
      category: "comforter",
      brand: "IKEA",
      model: "004.585.84",
      variantFamily: "SMÅSPORRE",
      name: "SMÅSPORRE 四季被 200×200 cm（004.585.84）",
      type: "synthetic",
      budget: "mid",
      price: 1699,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/883/0788308_PE763565_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/smasporre-art-00458584",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：化纖四季被；雙人方形；固定二件式",
        "組合內容：涼被 1 件＋暖被 1 件，可用固定扣結合",
        "表布材質：65% 再生聚酯纖維、35% 棉",
        "填充材質：100% 再生聚酯中空纖維",
        "填充比例／蓬鬆度：再生聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：四季；4＋7.5 TOG，可分用或扣合",
        "尺寸：長 200 x 寬 200 cm",
        "填充重量：涼被 0.6 kg；暖被 1.12 kg",
        "重量：涼被 1.44 kg；暖被 1.96 kg",
        "認證／產地：IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗、最高 80°C 烘乾；不可漂白、熨燙、乾洗",
      ],
      description: "SMÅSPORRE 的 200×200 cm 官方尺寸版，適合偏好方形被芯或兩人共用。涼被與暖被都有獨立 article 與分件重量證據。",
      pros: ["200×200 cm 方形尺寸", "固定二件式四季調整", "60°C 可機洗"],
      cons: ["台灣常見被套尺寸需先核對", "扣合後較重", "聚酯填充非天然材質"],
      bestFor: "使用 200×200 cm 被套、希望雙人四季彈性的人。",
      recommendation: "雙人四季候選：購買前先量現有被套；不可用顏色或套裝差異當另一款。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["四季推薦", "二件式", "雙人方形"],
    },
    {
      id: "comforter-hiyori-thin-deat3aa900bfnyl",
      category: "comforter",
      brand: "日和賞",
      model: "DEAT3A-A900BFNYL",
      variantFamily: "日和賞 MIT 夏季薄被胎",
      name: "MIT 夏季薄被胎雙人 180×210 cm（DEAT3A-A900BFNYL）",
      type: "synthetic",
      budget: "value",
      price: 750,
      image: "https://img.pchome.com.tw/cs/items/DEAT3AA900BFNYL/000001_1628663450.jpg",
      url: "https://24h.pchome.com.tw/prod/DEAT3A-A900BFNYL",
      label: "PChome 24h",
      specs: [
        "類型：化纖夏季薄被胎；雙人；單件成品",
        "組合內容：薄被胎 1 件",
        "表布材質：100% 聚酯纖維（通路未分列表布與填充）",
        "填充材質：100% 聚酯纖維（通路整體材質標示）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：夏季與冷氣房；輕薄被胎，非單純毛毯",
        "尺寸：寬 180 x 長 210 cm",
        "填充重量：查不到",
        "重量：約 1 kg",
        "認證／產地：BSMI M55495；台灣製",
        "清潔保養：可水洗；依洗標洗滌並平日曝曬約 1–2 小時，不可在未檢查前下水",
      ],
      description: "台灣製、可水洗的單件夏季薄被胎，180×210 cm、整件約 1 kg。通路沒有把填充重與整件重拆開，因此填充重量誠實標為查不到。",
      pros: ["750 元台灣新品", "整件可水洗且好收納", "雙人 180×210 cm"],
      cons: ["表布與填充未分列", "填充重量查不到", "保暖度不適合寒冬"],
      bestFor: "預算優先、想把薄被套改成夏季被芯的雙人使用者。",
      recommendation: "高 CP 夏季被胎：它是完整被胎而非毛毯；怕冷者冬季需另備暖被。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，個人衛生用品退換依通路規範。",
      tags: ["高 CP 值", "台灣製", "夏季被胎"],
    },
    {
      id: "comforter-ikea-bruksvara-60560475",
      category: "comforter",
      brand: "IKEA",
      model: "605.604.75",
      variantFamily: "BRUKSVARA",
      name: "BRUKSVARA 暖被 150×200 cm（605.604.75）",
      type: "synthetic",
      budget: "value",
      price: 799,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/800/1180030_PE896184_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/bruksvara-art-60560475",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：化纖暖被；單人；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 再生聚酯纖維",
        "填充材質：100% 聚酯纖維（至少 90% 再生）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；暖度由官方品名界定，TOG 未標示",
        "尺寸：長 200 x 寬 150 cm",
        "填充重量：0.86 kg",
        "重量：1.41 kg",
        "認證／產地：再生材質比例依 IKEA 原頁；產地原頁未標示",
        "清潔保養：60°C 機洗、最高 80°C 烘乾；不可漂白、熨燙、乾洗",
      ],
      description: "本類最低價的可信台灣新品之一，單人 150×200 cm、1.41 kg；適合先用低成本確認化纖暖被體感。",
      pros: ["799 元官方新品", "尺寸與淨重清楚", "60°C 可機洗"],
      cons: ["表布與填充皆為聚酯", "TOG 未標示", "單一暖度"],
      bestFor: "租屋、客房或先從低預算暖被開始的人。",
      recommendation: "入門推薦：適合客房與單人使用；若在意天然觸感改看羊毛、棉或羽絨。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["高 CP 值", "單人", "可機洗"],
    },
    {
      id: "comforter-ikea-bruksvara-20560477",
      category: "comforter",
      brand: "IKEA",
      model: "205.604.77",
      variantFamily: "BRUKSVARA",
      name: "BRUKSVARA 暖被 200×200 cm（205.604.77）",
      type: "synthetic",
      budget: "value",
      price: 899,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/800/1180030_PE896184_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/bruksvara-art-20560477",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：化纖暖被；雙人方形；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 再生聚酯纖維",
        "填充材質：100% 聚酯纖維（至少 90% 再生）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；暖度由官方品名界定，TOG 未標示",
        "尺寸：長 200 x 寬 200 cm",
        "填充重量：1.15 kg",
        "重量：1.85 kg",
        "認證／產地：再生材質比例依 IKEA 原頁；產地原頁未標示",
        "清潔保養：60°C 機洗、最高 80°C 烘乾；不可漂白、熨燙、乾洗",
      ],
      description: "200×200 cm 的 BRUKSVARA 官方尺寸版，維持不到千元的價格；1.15 kg 填充與 1.85 kg 整件重量分開記錄。",
      pros: ["不到千元的雙人方形款", "可 60°C 機洗", "exact article 尺寸版"],
      cons: ["聚酯觸感與透氣性需接受", "TOG 未標示", "被套尺寸需核對"],
      bestFor: "已有 200×200 cm 被套、預算優先的雙人使用者。",
      recommendation: "低價雙人候選：先確認被套；不因相同圖片而忽略 article 與尺寸差異。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["高 CP 值", "雙人方形", "可機洗"],
    },
    {
      id: "comforter-best-tencel-qfav6za9009hy1d",
      category: "comforter",
      brand: "BEST 貝思特",
      model: "QFAV6Z-A9009HY1D",
      variantFamily: "BEST 天絲保暖被",
      name: "天絲保暖被雙人 180×210 cm（QFAV6Z-A9009HY1D）",
      type: "synthetic",
      budget: "value",
      price: 1112,
      image: "https://img.pchome.com.tw/cs/items/QFAV6ZA9009HY1D/000001_1734342132.jpg",
      url: "https://24h.pchome.com.tw/prod/QFAV6Z-A9009HY1D",
      label: "PChome 24h",
      specs: [
        "類型：天絲混填化纖保暖被；雙人；單件成品",
        "組合內容：保暖被 1 件；另贈收納盒不作商品變體",
        "表布材質：100% 聚酯舒棉布",
        "填充材質：50% 天絲纖維、50% 超細纖維",
        "填充比例／蓬鬆度：天絲 50%／超細纖維 50%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；通路標示蓄熱保暖，未列 TOG／CLO",
        "尺寸：寬 180 x 長 210 cm",
        "填充重量：查不到",
        "重量：約 2.5 kg",
        "認證／產地：BSMI M45409；台灣製",
        "清潔保養：可乾洗；不可水洗、漂白、烘乾或熨燙",
      ],
      description: "50% 天絲纖維與 50% 超細纖維混填的台灣製雙人保暖被，整件約 2.5 kg。贈送收納盒不另計為版本。",
      pros: ["台灣製且價格低", "天絲／超細纖維比例明示", "雙人標準尺寸"],
      cons: ["填充重量未獨立標示", "不可水洗", "表布仍為聚酯纖維"],
      bestFor: "希望以低預算取得帶天絲混填與厚實壓感的雙人使用者。",
      recommendation: "高 CP 保暖被：先確認可接受約 2.5 kg 與乾洗保養；贈品不影響本款身分。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，個人衛生用品退換依通路規範。",
      tags: ["高 CP 值", "台灣製", "天絲混填"],
    },
    {
      id: "comforter-ikea-fjallarnika-30459025",
      category: "comforter",
      brand: "IKEA",
      model: "304.590.25",
      variantFamily: "FJÄLLARNIKA",
      name: "FJÄLLARNIKA 羽毛羽絨暖被 150×200 cm（304.590.25）",
      type: "down",
      budget: "mid",
      price: 1499,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/881/0788108_PE763470_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/fjallarnika-art-30459025",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：羽毛羽絨暖被；單人；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 棉",
        "填充材質：90% 鴨毛、10% 鴨絨",
        "填充比例／蓬鬆度：鴨毛 90%／鴨絨 10%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；暖度由官方品名界定",
        "尺寸：長 200 x 寬 150 cm",
        "填充重量：0.97 kg",
        "重量：1.815 kg",
        "認證／產地：IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗，使用約 1/3 洗劑並以 80°C 烘至全乾；不可漂白、熨燙、乾洗",
      ],
      description: "棉表布搭配 90% 鴨毛與 10% 鴨絨，價格低於高含絨款；保暖主要來自羽毛填充，重量與蓬鬆感取向不同。",
      pros: ["100% 棉表布", "羽毛羽絨天然填充", "單人尺寸與淨重完整"],
      cons: ["鴨絨僅 10%", "需烘至全乾避免結團", "對羽毛氣味敏感者需試用"],
      bestFor: "想從棉表布羽毛被入門、不追求高含絨輕量的人。",
      recommendation: "羽毛入門：重視含絨率者改看 FJÄLLBRÄCKA；清洗後務必徹底烘乾。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["棉表布", "羽毛羽絨", "單人"],
    },
    {
      id: "comforter-ikea-fjallarnika-70459028",
      category: "comforter",
      brand: "IKEA",
      model: "704.590.28",
      variantFamily: "FJÄLLARNIKA",
      name: "FJÄLLARNIKA 羽毛羽絨暖被 200×200 cm（704.590.28）",
      type: "down",
      budget: "mid",
      price: 1999,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/881/0788109_PE763469_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/fjallarnika-art-70459028",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：羽毛羽絨暖被；雙人方形；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 棉",
        "填充材質：90% 鴨毛、10% 鴨絨",
        "填充比例／蓬鬆度：鴨毛 90%／鴨絨 10%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；暖度由官方品名界定",
        "尺寸：長 200 x 寬 200 cm",
        "填充重量：1.29 kg",
        "重量：2.41 kg",
        "認證／產地：IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗，使用約 1/3 洗劑並以 80°C 烘至全乾；不可漂白、熨燙、乾洗",
      ],
      description: "FJÄLLARNIKA 200×200 cm 官方尺寸版，棉表布、90/10 羽毛羽絨，整件 2.41 kg。",
      pros: ["棉表布", "雙人方形 exact article", "天然羽毛填充"],
      cons: ["2.41 kg 不屬輕量", "含絨率低", "清洗後需足量烘乾"],
      bestFor: "偏好棉表布、已有方形被套且能接受羽毛重量的雙人使用者。",
      recommendation: "雙人羽毛候選：先核對被套與烘衣設備；高含絨輕量需求改選其他款。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["棉表布", "羽毛羽絨", "雙人方形"],
    },
    {
      id: "comforter-shikoku-washable-debclla900jcc6a",
      category: "comforter",
      brand: "四國纖維",
      model: "DEBCLL-A900JCC6A",
      variantFamily: "四國纖維 可水洗好眠四季被",
      name: "可水洗好眠四季被雙人 180×210 cm（DEBCLL-A900JCC6A）",
      type: "synthetic",
      budget: "mid",
      price: 5856,
      image: "https://img.pchome.com.tw/cs/items/DEBCLLA900JCC6A/000001_1760426506.jpg",
      url: "https://24h.pchome.com.tw/prod/DEBCLL-A900JCC6A",
      label: "PChome 24h",
      specs: [
        "類型：吸濕速乾化纖四季被；雙人；單件成品",
        "組合內容：四季被 1 件",
        "表布材質：樹脂纖維 85%、棉 15%（SEK 加工）",
        "填充材質：100% 樹脂纖維（duo 吸濕速乾纖維）",
        "填充比例／蓬鬆度：樹脂纖維 100%；蓬鬆度未標示",
        "適用季節／保暖性：四季；三種官方厚薄中本頁為中棉 0.8 kg 版本",
        "尺寸：寬 180 x 長 210 cm",
        "填充重量：0.8 kg",
        "重量：約 1.7 kg",
        "認證／產地：BSMI M54789、SEK 加工；日本製",
        "清潔保養：放入合適洗衣袋，以 40°C 以下輕柔機洗；不可烘乾",
      ],
      description: "日本製雙人四季被，中棉 0.8 kg、整件約 1.7 kg；SEK 加工表布與吸濕速乾填充適合重視可機洗潔淨的人。",
      pros: ["填充與整件重量分列", "日本製、SEK 加工", "可低溫輕柔機洗"],
      cons: ["價格高於多數化纖四季被", "不可烘乾", "洗衣機建議 8–10 kg 以上"],
      bestFor: "希望四季使用、重視抗菌消臭與可機洗的雙人家庭。",
      recommendation: "四季推薦：本頁是中棉 0.8 kg 的獨立商品，不以同系列其他厚薄另增款。",
      warranty: "PChome 24h 台灣新品、鈴木太太公司貨；原頁未列獨立年限保固，售後依通路與代理商規範。",
      tags: ["四季推薦", "日本製", "可機洗"],
    },
    {
      id: "comforter-ikea-fjallbracka-70537385",
      category: "comforter",
      brand: "IKEA",
      model: "705.373.85",
      variantFamily: "FJÄLLBRÄCKA",
      name: "FJÄLLBRÄCKA 再生羽絨暖被 150×200 cm（705.373.85）",
      type: "down",
      budget: "mid",
      price: 2999,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/882/0788248_PE763542_S4.jpg",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/fjallbracka-art-70537385",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：再生水禽羽絨羽毛暖被；單人；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 棉",
        "填充材質：60% 再生水禽羽絨、40% 再生水禽羽毛",
        "填充比例／蓬鬆度：羽絨 60%／羽毛 40%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；暖度由官方品名界定",
        "尺寸：長 200 x 寬 150 cm",
        "填充重量：0.5 kg",
        "重量：1.565 kg",
        "認證／產地：再生水禽填充、IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗，使用約 1/3 洗劑並以 80°C 烘至全乾；不可漂白、熨燙、乾洗",
      ],
      description: "60% 再生水禽羽絨比 FJÄLLARNIKA 含絨率高，單人款填充 0.5 kg、整件 1.565 kg。",
      pros: ["60% 羽絨", "100% 棉表布", "相對較輕"],
      cons: ["使用再生水禽填充，接受度因人而異", "蓬鬆度未標示", "需徹底烘乾"],
      bestFor: "重視含絨率與較輕重量、接受再生填充的單人使用者。",
      recommendation: "含絨率優先候選：仍需確認對羽絨氣味與再生材料接受度。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["60% 羽絨", "棉表布", "單人"],
    },
    {
      id: "comforter-ikea-fjallbracka-10537388",
      category: "comforter",
      brand: "IKEA",
      model: "105.373.88",
      variantFamily: "FJÄLLBRÄCKA",
      name: "FJÄLLBRÄCKA 再生羽絨暖被 200×200 cm（105.373.88）",
      type: "down",
      budget: "premium",
      price: 3799,
      image: "https://www.ikea.com.tw/dairyfarm/tw/images/882/0788249_PE763541_S2.webp",
      url: "https://www.ikea.com.tw/zh/products/duvets-pillows-and-protectors/duvets/fjallbracka-art-10537388",
      label: "IKEA 台灣官方商城",
      specs: [
        "類型：再生水禽羽絨羽毛暖被；雙人方形；單件成品",
        "組合內容：暖被 1 件",
        "表布材質：100% 棉",
        "填充材質：60% 再生水禽羽絨、40% 再生水禽羽毛",
        "填充比例／蓬鬆度：羽絨 60%／羽毛 40%；蓬鬆度未標示",
        "適用季節／保暖性：冷氣房至冬季；7.5 TOG",
        "尺寸：長 200 x 寬 200 cm",
        "填充重量：0.67 kg",
        "重量：2.055 kg",
        "認證／產地：再生水禽填充、IKEA of Sweden 設計；產地原頁未標示",
        "清潔保養：60°C 機洗，使用約 1/3 洗劑並以 80°C 烘至全乾；不可漂白、熨燙、乾洗",
      ],
      description: "200×200 cm、7.5 TOG 的 60/40 再生羽絨羽毛暖被；exact article 與尺寸不和單人款混用。",
      pros: ["60% 羽絨與 7.5 TOG", "棉表布", "官方雙人方形尺寸"],
      cons: ["被套相容性需核對", "蓬鬆度未標示", "再生填充偏好因人而異"],
      bestFor: "使用 200×200 cm 被套、重視含絨率的雙人使用者。",
      recommendation: "雙人羽絨推薦：以 7.5 TOG 評估室溫，不把單人版價格或證據套用。",
      warranty: "IKEA 台灣官方新品；依台灣退換貨與品質保證條款，棉被頁未列獨立保固年限。",
      tags: ["60% 羽絨", "7.5 TOG", "雙人方形"],
    },
    {
      id: "comforter-3m-nz370-m",
      category: "comforter",
      brand: "3M",
      model: "NZ370-M",
      variantFamily: "3M 新2代發熱纖維暖冬被 NZ370",
      name: "新2代發熱纖維暖冬被標準雙人 180×210 cm（NZ370-M）",
      type: "synthetic",
      budget: "premium",
      price: 8490,
      image: "https://img.91app.com/webapi/imagesV3/Original/SalePage/4612154/0/639155856355200000?v=1",
      url: "https://shop.3m.com.tw/SalePage/Index/4612154",
      label: "3M 台灣官方旗艦店",
      specs: [
        "類型：發熱纖維暖冬被；標準雙人；單件成品",
        "組合內容：暖冬被 1 件",
        "表布材質：100% 棉",
        "填充材質：100% 聚酯纖維（含吸濕發熱纖維）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：冬季；CLO 6，官方標示適用室溫 18–24°C",
        "尺寸：寬 180 x 長 210 cm",
        "填充重量：查不到",
        "重量：約 2.49 kg",
        "認證／產地：3M ID 7100134151、UPC 4710367436225、BSMI M34661；台灣製",
        "清潔保養：建議 20 kg 以上洗衣機水洗；60°C 以下低溫烘乾，依官方洗標操作",
      ],
      description: "3M 台灣官方 exact NZ370-M 標準雙人頁，CLO 6、整件約 2.49 kg，可水洗並低溫烘乾；填充重量未獨立公開。",
      pros: ["台灣官方旗艦店 exact 型號", "CLO 6 與適用室溫明示", "可水洗、低溫烘乾"],
      cons: ["售價較高", "填充重量查不到", "建議使用 20 kg 以上洗衣機"],
      bestFor: "冬季怕冷、重視可清洗與台灣官方售後的雙人家庭。",
      recommendation: "冬季保暖推薦：依 18–24°C 官方條件評估，不把同系列 NZ250／NZ500 當額外款計數。",
      warranty: "3M 台灣官方旗艦店新品；可由台灣官方商城與客服處理售後，頁面未列獨立年限保固。",
      tags: ["冬季保暖推薦", "CLO 6", "台灣官方"],
    },
    {
      id: "comforter-muji-jaap6a6s",
      category: "comforter",
      brand: "MUJI",
      model: "JAAP6A6S",
      variantFamily: "MUJI 防蟎羽毛薄被",
      name: "防蟎羽毛薄被 S 150×210 cm（JAAP6A6S／11617453）",
      type: "down",
      budget: "premium",
      price: 3590,
      image: "https://img.91app.com/webapi/imagesV3/Original/SalePage/11617453/0/639205154099200000?v=1",
      url: "https://shop.muji.tw/SalePage/Index/11617453",
      label: "MUJI 台灣官方商城",
      specs: [
        "類型：羽絨羽毛薄被；S 單人；單件成品",
        "組合內容：薄被 1 件",
        "表布材質：100% 聚酯纖維",
        "填充材質：80% 羽絨、20% 羽毛",
        "填充比例／蓬鬆度：羽絨 80%／羽毛 20%；蓬鬆度未標示",
        "適用季節／保暖性：春秋、冷氣房與換季；官方定義為薄被",
        "尺寸：長 210 x 寬 150 cm",
        "填充重量：0.2 kg",
        "重量：0.77 kg",
        "認證／產地：防蟎標示；印尼製",
        "清潔保養：建議加被套並通風陰乾；局部或專業清潔依官方洗標，不以高濕環境久置",
      ],
      description: "80% 羽絨、整件僅 0.77 kg 的單人薄被，偏向冷氣房與換季，而不是極寒冬被。",
      pros: ["80% 羽絨", "0.77 kg 輕量", "MUJI 台灣官方 exact SKU"],
      cons: ["表布為聚酯", "填充僅 0.2 kg", "不適合極冷室溫"],
      bestFor: "怕重、冷氣房與換季使用的單人使用者。",
      recommendation: "換季推薦：把它當薄被而非冬被；怕冷者另搭較高填充款。",
      warranty: "MUJI 台灣官方商城新品；原頁未列獨立年限保固，拆封寢具退換依台灣商城規範。",
      tags: ["換季推薦", "80% 羽絨", "輕量", "單人"],
    },
    {
      id: "comforter-muji-jaap9a6s",
      category: "comforter",
      brand: "MUJI",
      model: "JAAP9A6S",
      variantFamily: "MUJI 防蟎羽毛薄被",
      name: "防蟎羽毛薄被 Q 210×210 cm（JAAP9A6S／11617456）",
      type: "down",
      budget: "premium",
      price: 4590,
      image: "https://img.91app.com/webapi/imagesV3/Original/SalePage/11617456/0/639205154094530000?v=1",
      url: "https://shop.muji.tw/SalePage/Index/11617456",
      label: "MUJI 台灣官方商城",
      specs: [
        "類型：羽絨羽毛薄被；Q 方形；單件成品",
        "組合內容：薄被 1 件",
        "表布材質：100% 聚酯纖維",
        "填充材質：80% 羽絨、20% 羽毛",
        "填充比例／蓬鬆度：羽絨 80%／羽毛 20%；蓬鬆度未標示",
        "適用季節／保暖性：春秋、冷氣房與換季；官方定義為薄被",
        "尺寸：長 210 x 寬 210 cm",
        "填充重量：0.28 kg",
        "重量：1.07 kg",
        "認證／產地：防蟎標示；印尼製",
        "清潔保養：建議加被套並通風陰乾；局部或專業清潔依官方洗標，不以高濕環境久置",
      ],
      description: "MUJI 210×210 cm 官方 Q 尺寸版，80% 羽絨、整件 1.07 kg；不可把 S 版證據跨套。",
      pros: ["80% 羽絨", "方形大尺寸仍僅 1.07 kg", "exact SKU 可回查"],
      cons: ["Q 被套尺寸需確認", "薄被不適合寒冬", "聚酯表布"],
      bestFor: "偏好輕量方形被芯、冷氣房或換季使用的人。",
      recommendation: "換季方形款：先確認 210×210 cm 被套，冬季怕冷者不要單用。",
      warranty: "MUJI 台灣官方商城新品；原頁未列獨立年限保固，拆封寢具退換依台灣商城規範。",
      tags: ["換季推薦", "80% 羽絨", "方形"],
    },
    {
      id: "comforter-muji-jabg2a6a",
      category: "comforter",
      brand: "MUJI",
      model: "JABG2A6A",
      variantFamily: "MUJI 可水洗聚酯纖維被",
      name: "可水洗聚酯纖維被 SD 170×210 cm（JABG2A6A／12072381）",
      type: "synthetic",
      budget: "premium",
      price: 3990,
      image: "https://img.91app.com/webapi/imagesV3/Original/SalePage/12072381/0/639227643199700000?v=1",
      url: "https://shop.muji.tw/SalePage/Index/12072381",
      label: "MUJI 台灣官方商城",
      specs: [
        "類型：可水洗化纖被；SD；單件成品",
        "組合內容：被芯 1 件",
        "表布材質：55% 聚酯纖維、45% 萊賽爾纖維",
        "填充材質：100% 聚酯纖維（其中 50% 再生）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：四季至冬季；原頁未給 TOG",
        "尺寸：長 210 x 寬 170 cm",
        "填充重量：1.5 kg",
        "重量：2.5 kg",
        "認證／產地：填充含 50% 再生聚酯；中國製",
        "清潔保養：依洗標局部清潔並通風陰乾；使用後以手整理填充，避免結團",
      ],
      description: "SD 170×210 cm、1.5 kg 聚酯填充；萊賽爾混紡表布和可水洗定位適合重視日常照護者。",
      pros: ["SD 台灣常見尺寸", "表布含 45% 萊賽爾", "填充與整件重量清楚"],
      cons: ["整件 2.5 kg", "填充仍為聚酯", "實際清洗須依洗標"],
      bestFor: "希望 SD 尺寸、可日常維護且不使用動物性填充的人。",
      recommendation: "四季化纖候選：清洗前看洗標與洗衣機容量，晾乾後手動整理填充。",
      warranty: "MUJI 台灣官方商城新品；原頁未列獨立年限保固，拆封寢具退換依台灣商城規範。",
      tags: ["四季推薦", "SD", "萊賽爾混紡"],
    },
    {
      id: "comforter-muji-jabg3a6a",
      category: "comforter",
      brand: "MUJI",
      model: "JABG3A6A",
      variantFamily: "MUJI 可水洗聚酯纖維被",
      name: "可水洗聚酯纖維被 D 190×210 cm（JABG3A6A／12072382）",
      type: "synthetic",
      budget: "premium",
      price: 4290,
      image: "https://img.91app.com/webapi/imagesV3/Original/SalePage/12072382/0/639227643199700000?v=1",
      url: "https://shop.muji.tw/SalePage/Index/12072382",
      label: "MUJI 台灣官方商城",
      specs: [
        "類型：可水洗化纖被；D；單件成品",
        "組合內容：被芯 1 件",
        "表布材質：55% 聚酯纖維、45% 萊賽爾纖維",
        "填充材質：100% 聚酯纖維（其中 50% 再生）",
        "填充比例／蓬鬆度：聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：四季至冬季；原頁未給 TOG",
        "尺寸：長 210 x 寬 190 cm",
        "填充重量：1.7 kg",
        "重量：2.8 kg",
        "認證／產地：填充含 50% 再生聚酯；中國製",
        "清潔保養：依洗標局部清潔並通風陰乾；使用後以手整理填充，避免結團",
      ],
      description: "D 190×210 cm 的官方尺寸版，填充 1.7 kg、整件 2.8 kg；尺寸與重量不從 SD 推算。",
      pros: ["D 尺寸", "萊賽爾混紡表布", "50% 再生聚酯填充"],
      cons: ["2.8 kg 偏重", "TOG 未標示", "填充為化纖"],
      bestFor: "需要 D 尺寸、偏好無動物性填充與本地官方通路者。",
      recommendation: "雙人化纖候選：先確認洗衣與晾曬空間，重量敏感者改選薄羽絨款。",
      warranty: "MUJI 台灣官方商城新品；原頁未列獨立年限保固，拆封寢具退換依台灣商城規範。",
      tags: ["四季推薦", "D", "萊賽爾混紡"],
    },
    {
      id: "comforter-hola-wool-016788504",
      category: "comforter",
      brand: "HOLA",
      model: "016788504",
      variantFamily: "HOLA 100%可水洗法國羊毛防蟎冬被",
      name: "100%可水洗法國羊毛防蟎冬被單人（016788504）",
      type: "wool",
      budget: "mid",
      price: 2180,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/h0d/hc5/12330913562654/000000000016788504-gallery-01-20241029161043307.jpg",
      url: "https://www.momoshop.com.tw/TP/TP0006553/goodsDetail/TP00065530008497",
      label: "momo HOLA 官方店",
      specs: [
        "類型：羊毛冬被；單人；完整被芯",
        "組合內容：冬被 1 件",
        "表布材質：100% 聚酯纖維",
        "填充材質：100% 法國羊毛",
        "填充比例／蓬鬆度：羊毛 100%；蓬鬆度不適用",
        "適用季節／保暖性：冬季；原頁建議約 16–18°C 室溫",
        "尺寸：長 210 x 寬 150 x 高 1 cm",
        "填充重量：1.1 kg",
        "重量：2 kg",
        "認證／產地：Woolmark Pure New Wool、TTRI 物理防蟎；中國製",
        "清潔保養：低溫柔洗或專業乾洗；不可漂白、烘乾、熨燙",
      ],
      description: "Top Pick 同系列單人尺寸版，1.1 kg 法國羊毛填充、整件 2 kg；Momo HOLA 官方店可回查 exact 貨號。",
      pros: ["100% 法國羊毛", "單人尺寸完整證據", "可低溫柔洗標示"],
      cons: ["聚酯表布", "2 kg 有壓感", "不可烘乾"],
      bestFor: "單人冬季、偏好羊毛溫度調節與台灣售後者。",
      recommendation: "單人羊毛推薦：不可把雙人版重量套用；低溫柔洗後需充分平整陰乾。",
      warranty: "HOLA 台灣官方店新品，可由台灣客服協助；原頁未列獨立年限保固，拆封寢具退換限制依通路規範。",
      tags: ["冬季保暖推薦", "羊毛", "單人"],
    },
    {
      id: "comforter-hola-down-014301109",
      category: "comforter",
      brand: "HOLA",
      model: "014301109",
      variantFamily: "HOLA 90/10可水洗長效防蟎羽絨薄被",
      name: "90/10可水洗長效防蟎羽絨薄被單人（014301109）",
      type: "down",
      budget: "mid",
      price: 3680,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/h9a/hbb/12614174539806/000000000014301109-gallery-01-20251117160520149.jpg",
      url: "https://www.momoshop.com.tw/TP/TP0006553/goodsDetail/TP00065530004585",
      label: "momo HOLA 官方店",
      specs: [
        "類型：羽絨薄被；單人；單件成品",
        "組合內容：薄被 1 件",
        "表布材質：100% 棉",
        "填充材質：90% 羽絨、10% 羽毛",
        "填充比例／蓬鬆度：羽絨 90%／羽毛 10%；720 FP",
        "適用季節／保暖性：冷氣房與換季；原頁建議約 22–24°C 室溫",
        "尺寸：長 210 x 寬 150 x 高 0.5 cm",
        "填充重量：0.3 kg",
        "重量：1.35 kg",
        "認證／產地：TTRI 防蟎與防竄絨測試；中國製",
        "清潔保養：低溫柔洗或專業乾洗、低溫烘乾；不可漂白、熨燙",
      ],
      description: "90% 羽絨、720 FP、0.3 kg 填充的單人薄被，官方建議室溫 22–24°C，定位明確不是純涼感薄毯。",
      pros: ["90% 羽絨與 720 FP", "棉表布", "防蟎與防竄絨測試"],
      cons: ["薄被不適合寒冬", "填充僅 0.3 kg", "需小心清潔與乾燥"],
      bestFor: "冷氣房、換季、想要較高含絨率但不需厚冬被的人。",
      recommendation: "冷氣房推薦：室溫低於來源建議範圍時另加保暖層，不把冬被證據套用。",
      warranty: "HOLA 台灣官方店新品，可由台灣客服協助；原頁未列獨立年限保固，拆封寢具退換限制依通路規範。",
      tags: ["換季推薦", "90% 羽絨", "720 FP", "單人"],
    },
    {
      id: "comforter-hola-down-014381508",
      category: "comforter",
      brand: "HOLA",
      model: "014381508",
      variantFamily: "HOLA 90/10可水洗長效防蟎羽絨冬被",
      name: "90/10可水洗長效防蟎羽絨冬被加大（014381508）",
      type: "down",
      budget: "premium",
      price: 10980,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/h2b/hb0/12330816569374/000000000014381508-gallery-01-20241029155518623.jpg",
      url: "https://www.momoshop.com.tw/TP/TP0006553/goodsDetail/TP00065530008377",
      label: "momo HOLA 官方店",
      specs: [
        "類型：羽絨冬被；加大；單件成品",
        "組合內容：冬被 1 件",
        "表布材質：100% 棉",
        "填充材質：90% 羽絨、10% 羽毛",
        "填充比例／蓬鬆度：羽絨 90%／羽毛 10%；頁面同時標示 850 FP 與 650 FP，未擇一推定",
        "適用季節／保暖性：寒冷冬季；原頁建議約 12–14°C 室溫",
        "尺寸：長 240 x 寬 210 x 高 2 cm",
        "填充重量：查不到",
        "重量：2.98 kg",
        "認證／產地：OEKO-TEX Standard 100、RDS／DOWNPASS、TTRI、BV、IDFL；中國製",
        "清潔保養：40°C 柔洗或專業乾洗、低溫烘乾；不可漂白、熨燙",
      ],
      description: "加大 210×240 cm 的 90/10 羽絨冬被；來源填充重量誤列為 1200 kg，且蓬鬆度有 850／650 FP 衝突，本站保留不確定性而不自行修正。",
      pros: ["90% 羽絨與多項認證", "加大冬季尺寸", "12–14°C 保暖情境明示"],
      cons: ["填充重量來源單位明顯異常", "蓬鬆度兩處互相衝突", "整件 2.98 kg 且價格高"],
      bestFor: "需要加大厚冬被、願意先向官方確認蓬鬆度與填充重量的人。",
      recommendation: "冬季旗艦候選：下單前請 HOLA 以書面確認填充重量與 FP；本站不把頁面錯字改成推定值。",
      warranty: "HOLA 台灣官方店新品，可由台灣客服協助；原頁未列獨立年限保固，規格衝突宜於下單前書面確認。",
      tags: ["冬季保暖推薦", "90% 羽絨", "加大", "規格待確認"],
    },
    {
      id: "comforter-hola-real-014408625",
      category: "comforter",
      brand: "HOLA",
      model: "014408625",
      variantFamily: "HOLA REAL科技蠶絲防蟎冬被",
      name: "REAL極親膚科技蠶絲防蟎冬被雙人（014408625）",
      type: "synthetic",
      budget: "mid",
      price: 2624,
      image: "https://pcm.trplus.com.tw/1000x1000/sys-master/productImages/h04/hf4/12614222839838/000000000014408625-gallery-01-20251117160703567.jpg",
      url: "https://www.momoshop.com.tw/TP/TP0006553/goodsDetail/TP00065530010853",
      label: "momo HOLA 官方店",
      specs: [
        "類型：化纖冬被；雙人；官方品名使用科技蠶絲",
        "組合內容：冬被 1 件",
        "表布材質：100% 再生聚酯纖維",
        "填充材質：100% 再生聚酯纖維，非天然蠶絲",
        "填充比例／蓬鬆度：再生聚酯 100%；蓬鬆度未標示",
        "適用季節／保暖性：冬季；原頁建議約 20–22°C 室溫",
        "尺寸：長 213 x 寬 183 x 高 5.5 cm",
        "填充重量：1.35 kg",
        "重量：2.36 kg",
        "認證／產地：GRS 再生填充、Greenfirst、TTRI／BV／CNS 15290；中國製",
        "清潔保養：40°C 極柔洗、低溫烘乾；不可乾洗、熨燙、漂白",
      ],
      description: "官方品名雖寫「科技蠶絲」，規格明確是 100% 再生聚酯表布與填充，本站因此歸 synthetic，不冒充天然絲被。",
      pros: ["雙人 183×213 cm", "再生聚酯與多項測試", "填充／整件重量完整"],
      cons: ["不是天然蠶絲", "2.36 kg", "市售名稱可能造成材質誤解"],
      bestFor: "接受化纖、重視防蟎與可柔洗的雙人冬被使用者。",
      recommendation: "材質透明推薦：只按聚酯冬被比較；若要天然蠶絲請改選 silk 型態。",
      warranty: "HOLA 台灣官方店新品，可由台灣客服協助；原頁未列獨立年限保固，拆封寢具退換限制依通路規範。",
      tags: ["化纖", "雙人", "GRS", "材質透明"],
    },
    {
      id: "comforter-tanaka-silk-deatiwa900ayfmu",
      category: "comforter",
      brand: "田中保暖試驗所",
      model: "DEATIW-A900AYFMU",
      variantFamily: "田中保暖試驗所100%長纖蠶絲被",
      name: "100%長纖蠶絲夏被 3台斤 180×210 cm（DEATIW-A900AYFMU）",
      type: "silk",
      budget: "premium",
      price: 4674,
      image: "https://img.pchome.com.tw/cs/items/DEATIWA900AYFMU/000001_1706166136.jpg",
      url: "https://24h.pchome.com.tw/prod/DEATIW-A900AYFMU",
      label: "PChome 24h",
      specs: [
        "類型：天然蠶絲夏被；雙人；單件成品",
        "組合內容：蠶絲被 1 件",
        "表布材質：240 織、60 支、100% 棉",
        "填充材質：100% 天然長纖蠶絲",
        "填充比例／蓬鬆度：蠶絲 100%；蓬鬆度不適用",
        "適用季節／保暖性：夏季冷氣房與換季；通路定義 3 台斤夏被",
        "尺寸：長 210 x 寬 180 cm",
        "填充重量：查不到",
        "重量：約 1.8 kg",
        "認證／產地：BSMI M54132；台灣製",
        "清潔保養：不可水洗、乾洗、漂白、烘乾或熨燙；通風日曬保養",
      ],
      description: "100% 長纖蠶絲、棉表布的 3 台斤夏被；通路列約 1.8 kg 商品重量，但未把填充與整件重量分開。",
      pros: ["100% 長纖蠶絲", "棉表布", "台灣製與 BSMI"],
      cons: ["不可水洗或乾洗", "填充重量未獨立標示", "需防潮與妥善通風"],
      bestFor: "偏好天然蠶絲觸感、可接受細緻保養的冷氣房使用者。",
      recommendation: "天然絲被入門：重量是通路商品重量而非已證實填充量；不可自行送洗。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，天然蠶絲寢具退換與清潔責任依頁面。",
      tags: ["天然蠶絲", "台灣製", "夏季冷氣房"],
    },
    {
      id: "comforter-shikoku-sofair-deatgma900hqsfg",
      category: "comforter",
      brand: "四國纖維",
      model: "DEATGM-A900HQSFG",
      variantFamily: "四國纖維 SOFAIR WARM 無重力空氣暖被",
      name: "SOFAIR WARM 無重力空氣暖被雙人 190×210 cm（DEATGM-A900HQSFG）",
      type: "synthetic",
      budget: "premium",
      price: 9341,
      image: "https://img.pchome.com.tw/cs/items/DEATGMA900HQSFG/000001_1724216576.jpg",
      url: "https://24h.pchome.com.tw/prod/DEATGM-A900HQSFG",
      label: "PChome 24h",
      specs: [
        "類型：機能化纖冬被；雙人；單件成品",
        "組合內容：空氣暖被 1 件",
        "表布材質：100% 聚酯纖維；上層內裏含特殊鋁膜纖維布",
        "填充材質：70% 聚酯纖維、30% SUNBURNER® 合成纖維",
        "填充比例／蓬鬆度：聚酯 70%／SUNBURNER® 30%；蓬鬆度未標示",
        "適用季節／保暖性：冬季；通路測試被內溫度提升約 4.9°C",
        "尺寸：寬 190 x 長 210 cm",
        "填充重量：1.5 kg",
        "重量：約 1.9 kg",
        "認證／產地：表布中國加工、產品日本製；鈴木太太公司貨",
        "清潔保養：可水洗、機洗；依商品洗標並充分晾乾，不以包裝資訊代替本體規格",
      ],
      description: "日本製 SOFAIR WARM 獨立產品家族，1.5 kg 機能纖維填充、整件約 1.9 kg；特殊鋁膜內裏主打蓄熱。",
      pros: ["填充與整件重量完整", "日本製、可機洗", "通路提供 4.9°C 測試值"],
      cons: ["價格高", "表布與填充皆以化纖為主", "測試升溫值不等同所有室況"],
      bestFor: "冬季怕冷、想在較輕整件重量下取得蓄熱機能的雙人使用者。",
      recommendation: "冬季保暖推薦：4.9°C 為通路測試條件，不跨款當絕對排名；本家族只收此一 SKU。",
      warranty: "PChome 24h 台灣新品、鈴木太太公司貨；原頁未列獨立年限保固，售後依通路與代理商規範。",
      tags: ["冬季保暖推薦", "日本製", "蓄熱機能"],
    },
    {
      id: "comforter-tonia-graphene-debcb6a900gropd",
      category: "comforter",
      brand: "Tonia Nicole 東妮寢飾",
      model: "DEBCB6-A900GROPD",
      variantFamily: "Tonia Nicole 英威達抗菌七孔石墨烯冬被",
      name: "英威達抗菌七孔石墨烯冬被雙人 180×210 cm（DEBCB6-A900GROPD）",
      type: "synthetic",
      budget: "premium",
      price: 4980,
      image: "https://img.pchome.com.tw/cs/items/DEBCB6A900GROPD/000001_1733117996.jpg",
      url: "https://24h.pchome.com.tw/prod/DEBCB6-A900GROPD",
      label: "PChome 24h",
      specs: [
        "類型：化纖七孔石墨烯冬被；雙人；單件成品",
        "組合內容：冬被 1 件",
        "表布材質：100% 棉",
        "填充材質：100% 聚酯纖維（50% 英威達七孔纖維、50% 石墨烯纖維）",
        "填充比例／蓬鬆度：英威達七孔纖維 50%／石墨烯纖維 50%；蓬鬆度未標示",
        "適用季節／保暖性：冬季；通路實測一分鐘升溫 9.6°C",
        "尺寸：寬 180 x 長 210 cm",
        "填充重量：查不到",
        "重量：約 2.8 kg",
        "認證／產地：BSMI M36964；台灣製",
        "清潔保養：商品頁未明示洗滌程序；使用前依實品洗標，勿以同系列資料推定",
      ],
      description: "50% 英威達七孔纖維與 50% 石墨烯纖維的台灣製冬被，整件約 2.8 kg；通路未獨立提供填充重量。",
      pros: ["台灣製、BSMI 可回查", "填充比例清楚", "棉表布"],
      cons: ["填充重量查不到", "整件 2.8 kg 有壓感", "清潔程序未在商品頁標示"],
      bestFor: "冬季怕冷、偏好棉表布與較厚實壓感的雙人使用者。",
      recommendation: "冬季保暖候選：9.6°C 是通路測試描述；下水前必須以實品洗標為準。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，個人衛生用品退換依通路規範。",
      tags: ["冬季保暖推薦", "台灣製", "石墨烯纖維"],
    },
    {
      id: "comforter-belle-vie-wool-deatiba900c15jx",
      category: "comforter",
      brand: "BELLE VIE",
      model: "DEATIB-A900C15JX",
      variantFamily: "BELLE VIE 澳洲純羊毛被",
      name: "澳洲純羊毛被單人 135×195 cm（DEATIB-A900C15JX）",
      type: "wool",
      budget: "value",
      price: 1312,
      image: "https://img.pchome.com.tw/cs/items/DEATIBA900C15JX/000001_1637827645.jpg",
      url: "https://24h.pchome.com.tw/prod/DEATIB-A900C15JX",
      label: "PChome 24h",
      specs: [
        "類型：羊毛被；單人；單件成品",
        "組合內容：羊毛被 1 件",
        "表布材質：聚酯纖維",
        "填充材質：100% 澳洲小羊毛",
        "填充比例／蓬鬆度：羊毛 100%；蓬鬆度不適用",
        "適用季節／保暖性：秋冬；通路未列 TOG 或建議室溫",
        "尺寸：長 195 x 寬 135 cm",
        "填充重量：查不到",
        "重量：查不到",
        "認證／產地：BSMI M53995；台灣製",
        "清潔保養：通路規格未提供完整清洗流程；確認洗標前勿機洗",
      ],
      description: "價格低的 100% 澳洲小羊毛單人被；來源提供尺寸、材質與產地，但未提供填充重量、整件淨重及完整清潔方式。",
      pros: ["100% 澳洲小羊毛", "台灣製", "價格低"],
      cons: ["填充與整件重量查不到", "聚酯表布", "清潔流程未標示"],
      bestFor: "預算優先、願意先向通路確認重量與洗標的單人使用者。",
      recommendation: "平價羊毛候選：缺重資料是明確風險，下單前先向賣家索取洗標與淨重。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，尺寸公差與寢具退換依頁面。",
      tags: ["高 CP 值", "羊毛", "台灣製", "資料缺口"],
    },
    {
      id: "comforter-belle-vie-wool-deatiba900c15xv",
      category: "comforter",
      brand: "BELLE VIE",
      model: "DEATIB-A900C15XV",
      variantFamily: "BELLE VIE 澳洲純羊毛被",
      name: "澳洲純羊毛被雙人 180×210 cm（DEATIB-A900C15XV）",
      type: "wool",
      budget: "mid",
      price: 1412,
      image: "https://img.pchome.com.tw/cs/items/DEATIBA900C15XV/000001_1637830849.jpg",
      url: "https://24h.pchome.com.tw/prod/DEATIB-A900C15XV",
      label: "PChome 24h",
      specs: [
        "類型：羊毛被；雙人；單件成品",
        "組合內容：羊毛被 1 件",
        "表布材質：聚酯纖維",
        "填充材質：100% 澳洲小羊毛",
        "填充比例／蓬鬆度：羊毛 100%；蓬鬆度不適用",
        "適用季節／保暖性：秋冬；通路未列 TOG 或建議室溫",
        "尺寸：長 210 x 寬 180 cm",
        "填充重量：查不到",
        "重量：查不到",
        "認證／產地：BSMI M53995；台灣製",
        "清潔保養：通路規格未提供完整清洗流程；確認洗標前勿機洗",
      ],
      description: "同系列雙人 180×210 cm 官方通路 SKU，材質與尺寸可查，但不把單人或歐式加大重量跨版本套入。",
      pros: ["雙人常見尺寸", "100% 澳洲小羊毛", "台灣製"],
      cons: ["填充與淨重未標示", "聚酯表布", "清潔方式不完整"],
      bestFor: "預算有限、需要雙人羊毛被且能先補問資料的人。",
      recommendation: "雙人平價羊毛款：下單前確認實重、洗標與公差，不用其他尺寸版資料代替。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，尺寸公差與寢具退換依頁面。",
      tags: ["羊毛", "雙人", "台灣製", "資料缺口"],
    },
    {
      id: "comforter-belle-vie-wool-deatiba900aytrq",
      category: "comforter",
      brand: "BELLE VIE",
      model: "DEATIB-A900AYTRQ",
      variantFamily: "BELLE VIE 澳洲純羊毛被",
      name: "澳洲純羊毛被歐式加大 240×210 cm（DEATIB-A900AYTRQ）",
      type: "wool",
      budget: "mid",
      price: 2712,
      image: "https://img.pchome.com.tw/cs/items/DEATIBA900AYTRQ/000001_1604309455.jpg",
      url: "https://24h.pchome.com.tw/prod/DEATIB-A900AYTRQ",
      label: "PChome 24h",
      specs: [
        "類型：羊毛被；歐式加大；單件成品",
        "組合內容：羊毛被 1 件",
        "表布材質：聚酯纖維",
        "填充材質：100% 澳洲小羊毛",
        "填充比例／蓬鬆度：羊毛 100%；蓬鬆度不適用",
        "適用季節／保暖性：秋冬；通路未列 TOG 或建議室溫",
        "尺寸：長 210 x 寬 240 cm",
        "填充重量：查不到",
        "重量：約 2.9 kg",
        "認證／產地：BSMI M53995；台灣製",
        "清潔保養：通路規格未提供完整清洗流程；確認洗標前勿機洗",
      ],
      description: "240×210 cm 歐式加大、約 2.9 kg；來源未把羊毛填充重量獨立分列，本站只保留商品重量。",
      pros: ["歐式加大覆蓋", "100% 澳洲小羊毛", "台灣製"],
      cons: ["填充重量查不到", "約 2.9 kg", "被套相容性與清潔方式需確認"],
      bestFor: "需要 240 cm 寬大覆蓋、能接受較重羊毛被的人。",
      recommendation: "加大羊毛候選：先確認被套與洗衣設備；2.9 kg 是商品重量，不當成填充量。",
      warranty: "PChome 24h 台灣新品通路；原頁未列獨立年限保固，尺寸公差與寢具退換依頁面。",
      tags: ["羊毛", "歐式加大", "台灣製"],
    },
    {
      id: "comforter-owlting-organic-cotton-17469",
      category: "comforter",
      brand: "台灣有機棉",
      model: "OwlTing-17469",
      variantFamily: "台灣有機棉100%有機棉被胎",
      name: "100%台灣有機棉被胎單人 4.5×6.5尺（OwlTing-17469）",
      type: "cotton",
      budget: "premium",
      price: 6500,
      image: "https://static.owlting.com/market/public/items/thumbs/640x480/item_17469_b7fab2969a8dc1901a2565c50491bf4b",
      url: "https://market.owlting.com/items/17469",
      label: "OwlTing Market 奧丁丁市集",
      specs: [
        "類型：有機棉手工被胎；單人；單件成品",
        "組合內容：被胎 1 件",
        "表布材質：台灣有機棉被布",
        "填充材質：100% 台灣有機棉花",
        "填充比例／蓬鬆度：有機棉 100%；蓬鬆度不適用",
        "適用季節／保暖性：四季偏保暖；通路未列 TOG 或建議室溫",
        "尺寸：長 195 x 寬 135 cm",
        "填充重量：查不到",
        "重量：約 2.1 kg",
        "認證／產地：台灣有機農產品 1-004-100195、BVC、SGS 農藥檢測；台灣製",
        "清潔保養：被胎不可水洗；偶爾日曬 2–4 小時並輕拍",
      ],
      description: "台灣有機棉花、台灣手工製作的單人被胎；3.5 台斤約 2.1 kg 為頁面商品重量，沒有足夠資訊分離填充重量。",
      pros: ["台灣有機棉花與 MIT", "有機、BVC、SGS 證據", "手工被胎"],
      cons: ["不可水洗", "填充重量未分列", "2.1 kg 且需日曬空間"],
      bestFor: "偏好台灣植物纖維、可定期日曬保養的單人使用者。",
      recommendation: "親膚天然棉推薦：不可水洗是硬限制；潮濕住宅要先評估日曬與收納。",
      warranty: "OwlTing 台灣新品市集與台灣商家客服；原頁未列獨立年限保固，個人衛生用品拆封後退換受限。",
      tags: ["四季推薦", "台灣有機棉", "MIT", "單人"],
    },
    {
      id: "comforter-owlting-organic-cotton-17190",
      category: "comforter",
      brand: "台灣有機棉",
      model: "OwlTing-17190",
      variantFamily: "台灣有機棉100%有機棉被胎",
      name: "100%台灣有機棉被胎雙人薄被 6×7尺（OwlTing-17190）",
      type: "cotton",
      budget: "premium",
      price: 6500,
      image: "https://static.owlting.com/market/public/items/thumbs/640x480/item_17190_3aa8efe32f761c3a616048638c1e3f9a",
      url: "https://market.owlting.com/items/17190",
      label: "OwlTing Market 奧丁丁市集",
      specs: [
        "類型：有機棉手工被胎；雙人薄被；單件成品",
        "組合內容：被胎 1 件",
        "表布材質：台灣有機棉被布",
        "填充材質：100% 台灣有機棉花",
        "填充比例／蓬鬆度：有機棉 100%；蓬鬆度不適用",
        "適用季節／保暖性：四季偏薄；通路未列 TOG 或建議室溫",
        "尺寸：長 210 x 寬 180 cm",
        "填充重量：查不到",
        "重量：約 2.1 kg",
        "認證／產地：台灣有機農產品 1-004-100195、BVC、SGS 農藥檢測；台灣製",
        "清潔保養：被胎不可水洗；偶爾日曬 2–4 小時並輕拍",
      ],
      description: "180×210 cm 雙人薄被，頁面明列被布與填充都是台灣有機棉；3.5 台斤約 2.1 kg，填充量沒有分開標示。",
      pros: ["雙人台灣有機棉", "MIT 手工", "認證與清潔條件清楚"],
      cons: ["不可水洗", "薄被仍約 2.1 kg", "填充重量查不到"],
      bestFor: "偏好天然植物纖維、需要雙人尺寸且能日曬保養者。",
      recommendation: "雙人天然棉候選：不是水洗被；高濕環境要把日曬與防潮納入購買成本。",
      warranty: "OwlTing 台灣新品市集與台灣商家客服；原頁未列獨立年限保固，個人衛生用品拆封後退換受限。",
      tags: ["四季推薦", "台灣有機棉", "MIT", "雙人"],
    },
  ];

  dashboard.registerProducts("comforter", items.map(makeProduct));
})();
